- specification/paths/Services.json
*Changes*
- Add `with_contract` filter option to `GET /services` endpoint to only return services with active contracts or vice versa
*Related issues*
- https://myparcelcombv.atlassian.net/browse/MP-789
> Add with_contract filter to services endpoint

- specification/paths/Shipments.json
**Changes**
- Added `filter[carrier]` to `GET /shipments` endpoint
- https://myparcelcombv.atlassian.net/browse/MP-943
- https://myparcelcombv.atlassian.net/browse/MP-915
> Add carrier filter to GET /shipments endpoint

- specification/examples/PostShipmentRequest.json
- specification/schemas/BaseCustoms.json
**Changes**
- Added optional `license_number` and `certificate_number` properties to customs schema.
- https://myparcelcombv.atlassian.net/browse/MP-1189
> MP-1189 Added license_number and certificate_number to customs

- specification/paths/CarrierContracts.json
**Changes**
- Removed `carrier_contract_id` path parameter from `GET /carrier-contracts` endpoint
- https://myparcelcombv.atlassian.net/browse/MP-1316
> Remove carrier_contract_id path parameter from GET /carrier-contracts endpoint

- specification/schemas/ServiceOptionPrice.json
**Changes**
- Made amount of service option price non-required and nullable
- https://myparcelcombv.atlassian.net/browse/MP-1285
- https://myparcelcombv.atlassian.net/browse/MP-1282
> Make amount of service option price non-required and nullable

- package.json
- specification/info.json
- specification/schemas/Price.json
- specification/schemas/ServiceGroup.json
- specification/schemas/ServiceOptionPrice.json
- specification/schemas/ShipmentItem.json
**Changes**
- Removed `amount` from required attributes in `price` schema.
- Included `amount` in ShipmentItem `price` object object's array of required attributes.
- Included `amount` in ServiceGroup `step_price` object's array of required attributes.
- Replaced custom `price` schema in ServiceGroup `price` object by the `price` schema.
- Replaced custom `price` schema in ServiceOptionPrice `price` object by the `price` schema.
> Price amount is no longer required on shipment schemas.

- src/myparcelcom.css
The green `Authorize` button was located in a big white bar.
I made it float left to remove the need of this white area.
> :lipstick: moved auth button out of the white bar

- specification/schemas/Error.json
The `status` property should not be a number, but a string according to [the json-api spec](http://jsonapi.org/format/#error-objects).
While I was at it, I added some descriptions for clarification.
> Fixed non json-api complient error object and added descriptions

- specification/paths/Clients-client_id.json
Fixed bug where `links` was wrongly marked as required in `clients/{client_id}` endpoint
> Remove required links attribute from clients/{client_id} endpoint

- specification/paths/Clients.json
- specification/schemas/Client.json
**Changes**
- Removed required `links` property from post client response
- Removed `"additionalProperties": false` from Client resource
> Remove required links from post clients endpoint

- specification/paths/ServiceRates-service_rate_id.json
- specification/paths/ServiceRates.json
- specification/schemas/ServiceOptionsRelationship.json
- None
**Changes**
- Removed the links attribute from service options relationship schema, since our API never actually returns it.
> Removed links from service options relationship schema

- specification/paths/Shipments-shipment_id-Statuses-shipment_status_id.json
- specification/paths/Shipments-shipment_id.json
- specification/paths/Shipments.json
No related issue. This was reported via Marktplaats slack.
---
The `includes` of a shipment resource were not up2date with the API implementation.
> :memo: corrected the status includes of the shipment resource

- docker/build/default.conf
I noticed that requests to https://docs.develop.myparcel.com/api-specification were hanging. This will fix it.
> 🐛 This will make requests to /api-specification to work

- specification/schemas/BasePhysicalProperties.json
- [MP-2451](https://myparcelcombv.atlassian.net/browse/MP-2451) (Subtask)
- [MP-2409](https://myparcelcombv.atlassian.net/browse/MP-2409) (Story)
**Notes**
In case you were wondering about the formula being different than the one in the Epic, the one in the epic results in a volumetric weight in KG. Since we use grams as the unit for all of our weight properties, we can divide the volume (in mm3) by 5000 instead of 5000000 to get the volumetric weight in grams instead of KG.
> MP-2451 Added volumetric_weight to physical_properties schema.

- specification/schemas/IntegrationsRelationship.json
**Changes**
- Removed additionalProperties: false from the integrationsRelationship schema. It was causing problems when trying to add links to the response of the GET `/shops/{shop_id}/relationships/integrations` endpoint.
> Removed additional properties false from integrationsRelationship schema.

- specification/schemas/ShipmentSurcharge.json
- https://myparcelcombv.atlassian.net/browse/MP-2730
> 🐛 Fixed wrong example self link on shipment surcharges 

- specification/schemas/ShipmentSurcharge.json
- https://myparcelcombv.atlassian.net/browse/MP-2730
> 🐛 Fixed wrong example self link on shipment surcharges

- specification/paths/Regions-region_id.json
- specification/paths/Regions.json
- specification/paths/Services.json
- specification/schemas/Region.json
- specification/schemas/RegionCode.json
- src/myparcelcom.css
- Deprecated `GET /regions` endpoint.
- Deprecated `GET /regions​/{region_id}` endpoint.
- Deprecated service endpoint filters:
- `filter[region_from]`
- `filter[region_to]`
- `filter[address_from][region_code]`
- `filter[address_to][region_code]`
- Deprecated all `region_code` attributes. This affects:
- all Address objects
- all ServiceRegion objects
> MP-2733 ➖ Deprecated regions and region_code

- specification/schemas/SystemMessage.json
Patching to `null` was already possible. Now we can also post `null`.
> ♻️ Nullable system-message resource_type

- specification/paths.json
- specification/paths/ImportServiceRates.json
https://myparcelcombv.atlassian.net/browse/MP-3067
---
After discussing the usage of this endpoint, we will limit it to alter the service-rates for 1 contract. Therefore we only need a `contract_id` and the CSV `data`.
At the moment, our broker has 28 contracts in total. The front-end can still work with a broker/organization filter to select the contract, or even fire 4 requests to update all 4 tiers.
> MP-3067 ✨ Added import service sheet endpoint

- specification/paths.json
- specification/paths/Analytics-on-time-delivery.json
- specification/schemas.json
- specification/schemas/Analytics.json
- Introduced new endpoint for analytics (on time delivery stats)
- Introduced new schema for Analytics datasets
> 💹 Added /analytics/on-time-delivery path

- specification/schemas/RegionCode.json
https://myparcelcombv.atlassian.net/browse/MP-3484
- This field is deprecated and the validation blocks Shopify shipments.
- The API has no limitations and the database field is 255 characters.
> MP-3484 🔥 Removed region code validation

- specification/paths/Users-user_id.json
Otherwise all users need to get `users.manage` on their user resource.
> MP-3280 🔥 removed users:manage scope from user id endpoints

- specification/parameters.json
- specification/parameters/path-postal_code.json
- specification/parameters/query-city.json
- specification/parameters/query-street.json
- specification/parameters/query-street_number.json
- specification/paths.json
- specification/paths/Carriers-carrier_id-PickupDropoffLocations-country_code-postal_code.json
City is required for the DPD Parcelshopfinder to be able to return results.
Also moved `POST /registered-shipments` endpoint to show below regular `POST /shipments` endpoint in the sidebar.
> ♻️ Added city to pickup-dropoff parameters

- specification/schemas/Report.json
- https://myparcelcombv.atlassian.net/browse/MP-3757
- I actually started this implementation with the old non-nested date filters. Last sprint, we introduced the nested date filters, based on either `register_at` or `created_at`. This is a refactor that we also need in the specification for this reports endpoint.
> ✨ Added nested date filters to report schema.

- specification/parameters/header-files.json
- specification/paths.json
- specification/paths/Reports-report_id-Files-file_id.json
- Added new path /reports/{report_id}/files/{file_id} endpoint
- Endpoint accepts header is `text/csv` only since it is the only supported format
> Added Report file download path

- .circleci/config.yml
- kube/deployment.template.yaml
**Changes**
- Applied CircleCI contexts for aws and docker_cloud
- Docker Cloud only used for one image - `myparcelcom/build-utils`
- Applied configurable REGISTRY build argument on docker images. Defaults still to docker.io but .env template file has the ECR registry url by default
- https://myparcelcombv.atlassian.net/browse/MP-3878
- https://myparcelcombv.atlassian.net/browse/MP-2909
> 🔥 Deprecate Docker Cloud, use ECR

- specification/paths/HookLogs-hook_log_id.json
- specification/paths/Hooks-hook_id-logs.json
- specification/paths/Hooks-hook_id.json
- specification/paths/Hooks.json
Hooks and HookLogs should be accessible when you are allowed to manage shipments.
> MP-3943 🔒 Allow shipments.manage on hook related get endpoints

- specification/schemas/IntegrationsRelationship.json
It works fine when posted without `meta`.
> ♻️ Make shop-integration meta not required

- specification/paths/Carriers.json
This is actually not needed to achieve "Service filter should only show carriers available to organization".
And annoying to implement in the API, so let's revert this while it's still only in develop.
> ⏪ Remove has_active_contract filter on carriers endpoint

- specification/schemas/Status.json
This status has been introduced together with `shipment-voided` but has never been listed.
> ♻️ Add status cancelled

- specification/parameters/query-shipments-include.json
- specification/paths/RegisterMultiColliShipment.json
- specification/schemas.json
- specification/schemas/Shipment.json
- specification/schemas/ShipmentColliRelationship.json
https://myparcelcombv.atlassian.net/browse/MP-3613
- Add read-only `collo_number` to shipment attributes.
- Add read-only `colli` to shipment relationships and includes list.
- Update response of `/register-multi-colli-shipment` RPC endpoint.
> ✨ Add collo_number and colli to shipment resource

- root.json
- specification/paths/RegisterMultiColliShipment.json
- specification/paths/RegisteredShipments.json
- specification/schemas.json
- specification/schemas/Barcode.json
- specification/schemas/ColloNumber.json
- specification/schemas/Shipment.json
- specification/schemas/ShipmentColliRelationship.json
- specification/schemas/TrackingCode.json
- specification/schemas/TrackingUrl.json
https://myparcelcombv.atlassian.net/browse/MP-4170
- Fixed bug where `colli` relationship contained entire shipment resources instead of `id` + `type`.
- Added `meta` with base64 filedata to `colli` relationship of `/register-multi-colli-shipment` response.
- Fixed authentication token URL.
> MP-4229 ✨ Add meta with collo details to multi-colli response

- specification/schemas/ShipmentColliRelationship.json
https://myparcelcombv.atlassian.net/browse/MP-4237
- Shipment `colli` relationship should not contain entire Shipment resources.
> MP-4237 🚑️ Fix circular colli relationship

- specification/schemas/Shipment.json
- Introduced `recipient_tax_identification_numbers` and `sender_tax_identification_numbers` attributes on the Shipment schema.
- Marked `recipient_tax_number` and `sender_tax_number` attributes on the Shipment schema as **deprecated**.
- [Subtask] https://myparcelcombv.atlassian.net/browse/MP-4339
- [Story] https://myparcelcombv.atlassian.net/browse/MP-4334
> MP-4339 Tax Identification Number attributes on Shipment schema

- specification/schemas/Organization.json
- specification/schemas/PatchOrganization.json
We should mark these attributes as deprecated, and encourage the use of `tax_identification_numbers`.
> 🗑️ Deprecate old tax number attributes on organizations

- specification/paths/RegisteredShipments.json
- specification/paths/UpdateShipmentStatus.json
- specification/schemas/TaxIdentificationNumber.json
The description on the tax `number` attribute was too specific.
> ♿️ Sync tax-identification-number schema with carrier-specification

- specification/schemas/ServiceOption.json
- specification/schemas/ServiceOptionsRelationship.json
- specification/schemas/Shipment.json
- Added `values_format` meta property on ServiceOption schema.
- Added optional `meta.values` on `service_options` relationship in Shipment schema to allow users to pass on information specifically for a single service option.
- https://myparcelcombv.atlassian.net/browse/MP-4305 [Story]
- https://myparcelcombv.atlassian.net/browse/MP-4331 [Subtask]
> MP-4331 Service option meta

- specification/schemas/Shipment.json
- Fix incorrect type of `amount` example on service option relationship in Shipment schema.
> Incorrect type of service option value example

- specification/paths/Shipments-shipment_id.json
When introducing the `label.mime_type` we forgot to update the Shipment model used in the patch request.
> ♻️ Update patch shipment model to be in line with other shipment models

- specification/paths/Analytics-on-time-delivery.json
- specification/paths/Analytics-volume.json
- specification/paths/Regions.json
- specification/paths/Services.json
- specification/schemas/RegionRelationship.json
- specification/schemas/ServiceRegion.json
https://myparcelcombv.atlassian.net/browse/MP-4453
- Updated service regions and related filters:
- added `state_code`
- removed deprecated `region_code`
- Removed some examples that were redundant or not displayed correctly by the Redoc engine.
> MP-4453 ♻️ Added state_code to service regions

- specification/paths/RegisterMultiColliShipment.json
- Updated the service option ids on the multicolli endpoint to hold objects for service option values instead of just an array of service option ids.
> 🦺 MP 4541 api-spec service options values

- specification/paths/RegisterMultiColliShipment.json
> 💩 Fix multi-colli service option 'values' property structure

- specification/schemas/BaseCustoms.json
- Added `null` as a possible type for `shipment.attributes.customs.invoice_number` property.
- Added a description to `shipment.attributes.customs.invoice_number` property to indicate when it is required.
- https://myparcelcombv.atlassian.net/browse/MP-4368
> Invoice number should be nullable

- specification/schemas/BasePhysicalProperties.json
The `2147483647` is a standard upper limit for integers in programming (ES applies them too). Therefore, the physical properties should be limited under that max integer.
> 🚑 🐞 Added maximum values on physical properties

- specification/paths/Brokers-broker_id-carriers.json
- specification/paths/Brokers-broker_id-relationships-carriers.json
- specification/paths/Enterprises-enterprise_id.json
- specification/paths/Enterprises.json
Brokers have an Enterprise relationship, so the links in there should be retrievable with the same token. Since the broker endpoints have `broker.member` and `enterprises.manage` scopes, the enterprise endpoints should have this as well.
> ♻️ Allow broker members to get enterprises

- specification/schemas/HookTrigger.json
https://myparcelcombv.atlassian.net/browse/MP-4441
- Update hook predicates
- Added `in` as possible operator
- Added `array` as possible value type
> MP-4649 🧐 in operator for hooks

- specification/paths.json
- specification/paths/GetDynamicServiceRates.json
- specification/paths/ServiceRates-service_rate_id.json
- specification/paths/ServiceRates.json
- specification/schemas/ServiceRate.json
Subtask of https://myparcelcombv.atlassian.net/browse/MP-4367
- Added `is_dynamic` boolean to ServiceRate resource.
- Added `POST /get-dynamic-service-rates` endpoint.
- Allowed `shipments.manage` to retrieve ServiceRate resources (this is already possible in the API).
> MP-4657 ✨ Dynamic service-rates endpoint

- specification/paths/Manifests-manifest_id.json
- specification/paths/Manifests.json
- Introduced `contract` and `contract.carrier` include on manifests endpoints.
> ✨ Contract and carrier include on manifests

- specification/parameters/query-filter-created_at-date_from.json
- specification/parameters/query-filter-created_at-date_to.json
- specification/parameters/query-shipments-filter-register_at-date_from.json
- specification/parameters/query-shipments-filter-register_at-date_to.json
- specification/schemas/Report.json
When sending timestamps as date filters, the type is an integer (in the `POST /reports` body).
> ♻️ Allow integers as date filters

- specification/paths/Zones.json
- specification/schemas/Zone.json
Upon building the patch endpoint for the Zone resource I noticed that we made specific fields always required. This shouldnt be the case when patching a zone.
> Removed required fields 

- specification/tags.json
Zones are a resource and as such, they should be listed with the other endpoints, above RPC and analytics endpoints.
> Put zones with other resources in the list

- specification/paths/Zones-zone_id.json
- specification/paths/Zones.json
- specification/schemas/Zone.json
- specification/schemas/ZoneResponse.json
- Remove status attribute from zone resource.
- Order zone attributes to be in line with other resources.
> 🔥 Remove status attribute from zone resource

- specification/paths/Addresses-address_id.json
- specification/paths/Addresses.json
- specification/schemas.json
- specification/schemas/Address.json
- specification/schemas/AddressResponse.json
- specification/schemas/BrokerResponse.json
- specification/schemas/EnterpriseResponse.json
- specification/schemas/SystemMessageResponse.json
- specification/schemas/ZoneResponse.json
https://myparcelcombv.atlassian.net/browse/MP-4775
---
The `attributes` were required when patching an address, but this is not sent by our app when there are no changes.
I also introduced an `AddressResponse` (to avoid code duplication) and marked some `links` in responses as required because we always output them.
> 🐛 Restucture address setup to allow patch without attributes

- specification/paths/Hooks.json
- specification/schemas/HookTrigger.json
- Added `import` as possible `resource_action` on hooks.
- Removed `delete` as possible `resource_action` on hooks since it's not used and our docs also doesn't mention it.
- Added filter[trigger][resource_action] filter to the hooks endpoint. We already have filter[action_type]. Should we rename that to filter[action][action_type] :question: 
- https://myparcelcombv.atlassian.net/browse/MP-4812 - Subtask
- https://myparcelcombv.atlassian.net/browse/MP-4575 - Story
> ✨  Import resource action on hooks

- specification/paths/ServiceRates.json
- specification/schemas/ServiceRate.json
- Introduced `volumetric_weight_divisor` property on ServiceRate schema.
- Deprecated `filter[volumetric_weight]` filter on GET /service-rates endpoint.
- Introduced `filter[volume]` filter on GET /service-rates endpoint.
- https://myparcelcombv.atlassian.net/browse/MP-4674
> MP-4674 Dynamic volumetric weight calculation

- specification/schemas/FinalMileCarrier.json
Well, the final mile carrier country code can be skipped because it is always the same as the recipient country code.
> 🔥 Final mile carrier country code can be deprecated

- specification/paths/RegisteredShipments.json
- specification/paths/Shipments-shipment_id.json
- specification/paths/Shipments.json
- specification/paths/TrackExternalShipment.json
- specification/schemas/TrackingCode.json
- Avoid display issues due to `"readOnly": false`
- Apply POST data restrictions to `POST /registered-shipments` endpoint.
> 🐛 Avoid readOnly: false

- specification/parameters/path-latitude.json
- specification/parameters/path-longitude.json
Basically the `+` and `-` are allowed when specifying geo location, and also there are some ranges in the numbers for both. Therefore I changed the types to string and I have placed a regex I found on stack overflow
> 👌 Changed latitude/longitude types

- specification/paths/Collections-collection_id.json
- specification/schemas/Collection.json
- Shipments can now be posted as a relationship
- Only the `name` and `register` properties can be patched
> Patch Collections - Patchable fields in 🥶lections

- specification/parameters.json
- specification/parameters/header-idempotency-key.json
- specification/paths/RegisteredShipments.json
- specification/paths/Shipments.json
https://myparcelcombv.atlassian.net/browse/MP-4922
---
- Updated  `POST /shipments` and `POST /registered-shipments` endpoints:
- Added `Idempotency-Key` request header.
- Added `Idempotency-Replay` response header.
> ✨ Idempotency key and replay headers

- specification/schemas/Zone.json
The `state_codes` were defined as:
> an array, containing a StateCode or null
It should be:
> an array containing a StateCode, or null
> 🐛 Fix nullable zone state_codes

- specification/paths/Shipments.json
- Added meta property `add_to_next_collection` to the POST /shipments endpoint.
- https://myparcelcombv.atlassian.net/browse/MP-5174
- https://myparcelcombv.atlassian.net/browse/MP-5037
> :sparkles: MP-5174 Add shipment to next collection

- specification/paths/ExportRatesTemplate.json
The response was not visible in the spec because the indentation was wrong.
> 🐛 Fix response path for export-rates-template

- specification/paths/CreateManifestForCollection.json
- specification/paths/GetDynamicServiceRates.json
To enable `validate-json` middleware in our API, this endpoint should work with `application/vnd.api+json`.
Also there was an indentation issue in the manifest RPC endpoint, causing the response not to be shown.
> ♻️ get-dynamic-service-rates should accept json-api

- specification/paths/ConsolidateShipments.json
- specification/paths/CreateManifestForCollection.json
- specification/paths/GetDynamicServiceRates.json
- specification/paths/TrackExternalShipment.json
After discussing with the team, we should make RPC endpoints work with `application/json` regardless of the actual JSON.
The main reason is consistency and the fact that JSON:API is designed for REST endpoints (which RPC endpoints are not).
> ♻️ RPC endpoints should always work with application/json

- src/myparcelcom.js
- Removed POST `/registered-shipments` from list of experimental endpoints.
- https://myparcelcombv.atlassian.net/browse/MP-5128
> MP-5128 :fire: Remove registered shipments endpoint from experimental endpoints

- specification/schemas/Zone.json
We will add API validation to be able to output which country code is invalid.
> ♻️ Remove regex from zone country_codes to improve error messages

- specification/paths/MultiColliShipments.json
- specification/paths/RegisterMultiColliShipment.json
- specification/paths/RegisteredShipments.json
- specification/paths/Shipments.json
When sending another request with the same `Idempotency-Key` header, while the first request is still being processed, you will get a `423` conflict response.
> 📝 423 response for requests which support idempotency

- specification/schemas/CarrierStatus.json
- specification/schemas/TrackingCode.json
- Added `tracking_code` to carrier status schema
- Improved the description of the Shipment's `tracking_code` attribute.
- https://myparcelcombv.atlassian.net/browse/MP-5356
- https://myparcelcombv.atlassian.net/browse/MP-5296
> MP-5356 Tracking code on carrier statuses

- specification/schemas/Status.json
- We had a randomly failing test in the API that was choosing `collection-collected` as a status, but the API specification didn't have it as a possible value in its enum.
> :lady_beetle: Added collection-collected to status code enum.

- specification/paths/Organizations.json
- specification/paths/Shops.json
- specification/schemas/Organization.json
- specification/schemas/Shop.json
- Added `reference` attribute to shop and organization schemas
- Added `reference` as a field to use when searching organizations or shops
- https://myparcelcombv.atlassian.net/browse/MP-5370
- https://myparcelcombv.atlassian.net/browse/MP-5483
> :sparkles: MP-5483 Added reference to shop and organization schemas.

- specification/schemas/BaseShipmentItem.json
- Introduced `item_weight_unit` for shipment items.
- https://myparcelcombv.atlassian.net/browse/MP-5495
- https://myparcelcombv.atlassian.net/browse/MP-5254
> :sparkles: MP-5495 Added item_weight_unit property to shipment items

- specification/paths/CollectionSchedules.json
- specification/schemas.json
- specification/schemas/CollectionSchedule.json
- specification/schemas/CollectionScheduleTime.json
- Converted the date time / timestamp attribute into a timestring attribute since we don't need a date for those fields.
> MP-5566 Collection schedule time from and to into timestring

- root.json
- specification/paths/Hooks.json
- specification/schemas/ServiceRate.json
- specification/tags.json
- The new docs engine needs `.html`.
- The password resets are deprecated and have moved to the auth server.
> 🔗 Fixed broken links to the docs

- specification/paths/CombineFiles.json
The api specification lists that the `/combine-files` RPC endpoint response is `text/csv`. 
This is incorrect, I've changed it to `text/plain`.
> :lady_beetle: Fixed mime-type of /combine-files endpoint response.

- specification/paths/Manifests.json
- specification/schemas/Manifest.json
- specification/schemas/ManifestIncludes.json
- specification/schemas/ManifestResponse.json
Reverts MyParcelCOM/api-specification#810
Reverting since it's not implemented in the API yet. 
It is currently causing tests to fail in other pull requests that have the updated specification as a dependency. 
We can re-merge it when the functionality in the API is done and until then, development can be done using the dev-branch.
> Revert "Changed shop relationship to owner relationship for Manifests"

- specification/paths/Shops-shop_id.json
- specification/paths/Shops.json
In the specification for the request body for post and patch shops, we define the logo contents in a `meta` property that is a sibling of `data`. In other places where we send meta-data with post and patch requests, they reside inside of `data`. (rate-imports, user-scope relationships, and shop-integration relationships). According to the json-api specification, this is allowed and has the following description:
> `meta`: a [meta object](https://jsonapi.org/format/#document-meta) containing non-standard meta-information about a resource that can not be represented as an attribute or relationship.
This sounds a lot like what we're trying to achieve.
Using the top-level `meta` attribute (data's sibling) sounds more like we're sending meta-data about the request instead of the resource. This …
> :truck: Moved shop-meta inside of top-level data property.

- root.json
- specification/paths.json
- specification/paths/Returns-v1-shops-shop_id-orders-reference-email.json
- specification/schemas.json
- specification/schemas/Order.json
- specification/schemas/OrderItem.json
- specification/schemas/OrderResource.json
- specification/tags.json
- src/myparcelcom.js
- ✨ Added schema's for the Order resource and it's related schema's.
- ✨ Added the endpoint for retrieving orders
- ✨ Added the `returns.manage` scope to the list of scopes.
- https://myparcelcombv.atlassian.net/browse/MP-5922
- https://myparcelcombv.atlassian.net/browse/MP-5754
> MP-5922 :sparkles: Added endpoint and schemas for Return Order resources.

- specification/paths/Manifests-manifest_id.json
- specification/paths/Manifests.json
The include was never parsed by the API and our portal never used it either. We can drop this deprecated thing right now.
> 🔥 Manifest endpoints never supported the shop include

- specification/paths/Manifests.json
- specification/schemas/ManifestResponse.json
API tests `Failed to match exactly one schema` in a manifest response, which is enforced by `oneOf` so we better use `anyOf`.
> 🧵 Allow both owner and shop in the manifest response relationships

- specification/schemas/ReturnResponse.json
- Removed badly copied properties from the required fields
- Introduced response fields that should actually be required
> :beetle: Return response required fields

- specification/schemas/OrderItem.json
- specification/schemas/ReturnItem.json
- Introduced identifiers for Order item and Return item
- Removed name as required  property from the Return item since we can now identify by id.
> :heavy_plus_sign: Introduced identifiers for Order item and Return item

- specification/parameters.json
- specification/parameters/query-filter-owner.json
- specification/paths/Contracts.json
- specification/schemas/ManifestResource.json
- While working on the back office, I wanted to see what filters we have available on the GET /Contracts endpoint. To my surprise, the spec didn't have any listed. So I added the ones that are available according to the `ContractRepository` in our API.
> :sparkles: Added filters to the contracts endpoint.

- specification/schemas/ManifestResource.json
The `ManifestResource` is a generic resource which is extended with `attributes` and `relationships` by other resources.
Giving this `"additionalProperties": false` causes errors in our API on the manifest `getAll` response.
Since the inheritance of the additionalProperties between resources does not work as expected, we better revert and remove this.
> 🐛 No additionalProperties false on the ManifestResource

- specification/paths/Shops-shop_id-relationships-integrations.json
Since the integration `settings_format` is optional/nullable, the shop relationship meta should also not have `settings` required.
> ⏪️ ShopIntegration meta.settings should not be required

- specification/schemas/ContractsRelationship.json
This was refactored to `ContractResponse`, but it should have been `ContractResource`.
> 🐛 Fix refactoring issue in the ContractsRelationship schema

- specification/schemas/Contract.json
- specification/schemas/ContractResponse.json
A contract status can have 4 different values, but can only be patched to `active` or `inactive`.
Since the statuses `pending` and `invalid` are set by our API, they belong in the `ContractResponse` schema.
The OpenAPI `allOf` will merge everything so that the final response schema has all 4 values.
> 🐞 Separate contract status enum values

- specification/paths/Contracts-contract_id.json
- specification/schemas/Contract.json
- specification/schemas/ContractResponse.json
Defined the enum values in 2 places because our validation library does not recognize merged enum values through `allOf`.
> 🐛 Merged enums do not work properly with our validation library

- specification/parameters.json
- specification/parameters/path-pudo_id.json
- specification/paths.json
- specification/paths/Carriers-carrier_id-PickupDropoffLocations-pudo_id.json
- specification/schemas/Carrier.json
- specification/schemas/PickupDropoffLocation.json
https://myparcelcombv.atlassian.net/browse/MP-5565
---
- Added carrier attribute: `pudo.can_get_pudo_by_id`
- Added endpoint: `GET /carriers/{carrier_id}/pickup-dropoff-locations/{pudo_id}`
- Added `self` link to pudo resource.
> 🆔 Endpoint to get PUDO location by ID

- specification/paths/Returns-v1-returns.json
- specification/schemas/ReturnMethodResponse.json
- Make return method relationship required on returns
This was optional before so it wouldnt introduce failing tests while developing the API part for this feature.
> Make return method required

- specification/paths/Returns-v1-returns.json
- specification/schemas/Return.json
- specification/schemas/ReturnMethodResponse.json
- specification/schemas/ReturnResponse.json
The `return_method` relationship on a `ReturnMethodResponse` was required, but this needed to be set on a `ReturnResponse`.
I also updated the relationships to be in alphabetical order.
> 🐛 Make the correct return_method relationship required

- specification/schemas/BaseShipmentItem.json
This will prevent issues in DPD NL when weight calculations are not expecting `0`.
> 0️⃣ Prevent quantity and item_weight to be 0

- specification/paths/Returns-v1-reasons.json
- No relationships are required when creating a return reason
> :beetle: Remove required return reason relationships on post

- specification/paths/Returns-v1-reasons-return_reason_id.json
- specification/paths/Returns-v1-reasons.json
- specification/tags.json
- src/myparcelcom.js
As discussed during the demo, we can now hide the return reason management from the rest of the return reason endpoints
> :mute: Hide the return reason management under its own tag

- specification/paths/Organizations.json
- specification/paths/PasswordResets.json
- specification/paths/Shops.json
- specification/paths/Users-user_id.json
- specification/paths/Users.json
- specification/schemas/Shop.json
- specification/schemas/User.json
- specification/schemas/UserResponse.json
https://myparcelcombv.atlassian.net/browse/MP-3011
---
- Exposed the `username` of a user as a required attribute.
- Indicated that the `user.username` and `shop.name` should be unique.
- Updated the list of search fields to match the targeted attributes.
- Updated the `PasswordReset` to work with a `User` relationship instead of an email attribute.
Users and PasswordResets are marked as experimental endpoints, so we can make breaking changes in them.
> 👔 Separated the username and email of a user

- specification/paths/Returns-v1-return-methods.json
- specification/schemas/ReturnMethodResponse.json
https://myparcelcombv.atlassian.net/browse/MP-6141
---
- Remove the requirement of `default_weight`.
- Added description to indicate when it is required.
> ♻️ ReturnMethod default_weight is not always required

- specification/parameters/path-return_reason_id.json
- specification/paths/Returns-v1-reasons-return_reason_id.json
- specification/paths/Returns-v1-reasons.json
- specification/schemas/ReturnItem.json
- specification/schemas/ReturnReason.json
- 🚚 Moved GET return reason endpoints under ReturnReasons tag instead of ReturnReasonManagement.
- ✨ Added `reason` property to ReturnItem schema.
- https://myparcelcombv.atlassian.net/browse/MP-6166
- https://myparcelcombv.atlassian.net/browse/MP-6140
> MP-6166 Return item reason

- specification/paths/Users-user_id.json
- specification/paths/Users.json
https://myparcelcombv.atlassian.net/browse/MP-6192
---
Normal users don't have `users.manage` so we should allow GET and PATCH without a specific scope.
The API will make sure these interactions will be limited to the `user_id` from the token.
> Users should be able to get or patch themselves

- specification/paths.json
- specification/paths/Returns-v1-returns-return_id-retry-shipment.json
- specification/schemas/ReturnResponse.json
- Introduced `POST /returns/v1/returns/{return_id}/retry-shipment`
- Added `shipment_registrations` array in Return responses
> :sparkles: New endpoint for manual retry of return shipment registrations

- specification/schemas.json
- specification/schemas/Locale.json
- specification/schemas/Shop.json
- specification/schemas/ShopResponse.json
- specification/schemas/User.json
- ✨  Added `locale` attribute to the Shop schema.
- Made required only for ShopResponses as it will default to `en_GB`.
- https://myparcelcombv.atlassian.net/browse/MP-6233
> :sparkles: MP-6172 Added locale attribute to Shop schema.

- specification/paths/Hooks.json
- specification/schemas/ReturnResponse.json
**Related Jira Ticket**
https://myparcelcombv.atlassian.net/browse/MP-6167
P.S. oops, change to `Hooks.json` is here by accident, but I think they should be merged as well, since we're introducing Hooks for Returns this sprint
> :sparkles: add registration_retry_after and payments properties to ReturnResponse

- specification/schemas/ReturnResponse.json
The return payment IDs are not used for anything
> 🔥  Return payment IDs exposure is not needed

- specification/schemas/returns/MostReturnedItem.json
- Made `item` property required
- Moved `return_reasons` alongside `items` instead of inside it.
> 🚑 Fix most returned items response body

- specification/schemas/returns/ReturnAnalytics.json
- Made the `unit_type`, `labels` and `datasets` properties in `returns/v1/analytics/approved` endpoint response body required.
> ✨ Required properties in return analytics approved endpoint

- specification/paths/Returns-v1-returns.json
- specification/schemas.json
- specification/schemas/returns/ReturnSimpleResponse.json
- specification/schemas/statuses/Status.json
- specification/schemas/statuses/StatusLevel.json
When getting multiple returns, a meta field is added for each which contains the shipment (if any) tracking code and status code.
Removed the shipment include when getting multiple returns.
> ⚡  Added shipment metadata for ReturnSimpleResponse

- specification/schemas/returns/ReturnResponse.json
- Changed 'payments' to singular 'payment' in the ReturnResponse resource
- Introduced payment failures
> :sparkles: Added payment failures array on returns

- specification/paths/CalculateLandedCosts.json
Added because someone was passing a big number as `shipping_value`, probably confusing it with "shipment value".
> ♿️ Explain landed cost shipping_value

- specification/schemas/return-orders/OrderResponse.json
https://myparcelcombv.atlassian.net/browse/MP-6420
> :sparkles: add shipping_and_return and label_in_the_box meta properties to OrderResponse

- specification/schemas/shops/Shop.json
- Added three properties to hide order product details on the return portal:
- `hide_product_features`
- `hide_product_description`
- `hide_product_price`
- https://myparcelcombv.atlassian.net/browse/MP-6479
- https://myparcelcombv.atlassian.net/browse/MP-6462
> MP-6479 :sparkles: Added properties to hide product card details to Shop schema

- root.json
- specification/tags.json
- src/myparcelcom.css
The unicode characters in our specification make the JSON to YAML parser throw up.
> 🔗 Move unicode link icons to CSS

- specification/schemas/invitations/InvitationRequest.json
The back office inputs will go back to empty strings when they held a value that is removed. 
Our back office logic also converts empty strings to `null` when posting to the API.
The API specification did not allow `null` values, only strings. I think this is too strict, as in the end it makes no difference to leave out the value or send `null` (in a POST request, PATCH is a different story).
- 😶 Allow `null` value for invitation first and last names.
- https://myparcelcombv.atlassian.net/browse/MP-6567
> :no_mouth: Allow null values for invitation first name and last name.

- specification/schemas/shops/ShopResponse.json
It seems that the parent objects can hold values without the boolean properties being returned by our API.
Such is the case when for example only posting a logo and not any styling properties. 
Therefore, the boolean properties are not always present in the response when the parent is present, and the properties should not be required.
- 🔓  Made the boolean properties of the branding objects optional.
> :unlock: Optional boolean properties in branding objects.

- specification/paths/Returns-v1-returns.json
- specification/schemas/returns/ReturnItem.json
- specification/schemas/returns/ReturnResponse.json
- specification/schemas/returns/ReturnSimpleResponse.json
https://myparcelcombv.atlassian.net/browse/MP-6607
---
- Added `preferred_outcome` enum with values `refund` and `exchange` to ReturnItems.
- Added `has_preferred_outcome_refund` and `has_preferred_outcome_exchange` to Returns.
- Added `filter[has_preferred_outcome_refund]` and `filter[has_preferred_outcome_exchange]` to GET all returns.
> ✨ Added preferred outcome to returns and their items

- specification/paths/Organizations.json
- specification/paths/Shipments.json
- specification/paths/Shops.json
- specification/schemas/reports/Report.json
https://myparcelcombv.atlassian.net/browse/MP-3738
---
To be able to filter the shipment overview and the reports on the broker(s) that are selected (for multi-broker admins).
Meanwhile we also need to be able to limit the organization + shop filters to these broker for the values to make sense.
**Question**
Currently the carriers / contracts / services endpoints are internally filtered on all brokers the user + client have access to.
I guess we should also allow a `filter[broker]` to be passed via the URL so these values can be limited to just 1 broker?
> ✨ Introduce broker filters on endpoints for shipments and reports

- specification/paths/ServiceRates.json
- specification/schemas/service-rates/ServiceRate.json
- specification/schemas/services/Service.json
- specification/schemas/shipments/BasePhysicalProperties.json
https://myparcelcombv.atlassian.net/browse/MP-6722
---
- Moved the `volumetric_weight_divisor` attribute from service-rates to services.
- This is not a breaking change, since it was never implemented in our API
- Updated some descriptions to reflect this change.
- `filter[volume]` of service-rates
- `volumetric_weight` of shipments
> 🚚 Move volumetric_weight_divisor to services

- specification/parameters.json
- specification/parameters/path-demo_order_id.json
- specification/paths.json
- specification/paths/Returns-v1-demo-orders-demo_order_id.json
- specification/paths/Returns-v1-demo-orders.json
- specification/schemas.json
- specification/schemas/return-orders/DemoOrder.json
- specification/schemas/return-orders/DemoOrderResource.json
- specification/schemas/return-orders/DemoOrderResponse.json
- add specification for GET and POST `/returns/v1/demo-orders`
- add specification for GET `/returns/v1/demo-orders/{demo_order_id}`
https://myparcelcombv.atlassian.net/browse/MP-6732
> :sparkles: Manage demo orders specification

- specification/parameters/header-accept-language.json
- specification/paths/Manifests-manifest_id-Files-file_id.json
- specification/paths/RegisteredShipments.json
- specification/paths/Shipments-shipment_id.json
- specification/paths/Shipments.json
- specification/schemas/carriers/Carrier.json
- specification/schemas/files/CombinedFileResource.json
- specification/schemas/integrations/Integration.json
- specification/schemas/services/ServiceResponse.json
- specification/schemas/shipments/Shipment.json
- Moved `deprecated` definition to top of object structure
- Removed useless (`"required": "false"`) and deprecated required definitions (`region_from` and `region_to`)
> 🧹 Cleanup some required and deprecated definitions

- specification/schemas/service-rates/ServiceRate.json
- specification/schemas/service-rates/ServiceRateResponse.json
- Added `includes_vat` attribute to ServiceRate schema.
- https://myparcelcombv.atlassian.net/browse/MP-6785
> :sparkles: MP-6785 Added includes_vat to service rate attributes.

- specification/paths/ServiceRates.json
- specification/paths/Suggest-hscode.json
- specification/schemas/contracts/Contract.json
- specification/schemas/contracts/ContractResponse.json
- specification/schemas/integrations/OrderAnalytics.json
- specification/schemas/returns/MostReturnedItem.json
- specification/schemas/returns/ReturnAnalytics.json
- specification/schemas/service-rates/ServiceRate.json
- specification/schemas/services/Service.json
https://myparcelcombv.atlassian.net/browse/MP-6757
---
- Added `volumetric_weight_divisor_factor` float to the `Contract` resource.
- Adjusted existing number types to be defined according to [the OpenAPI Number definition](https://swagger.io/docs/specification/data-models/data-types/#numbers).
> OpenAPI has two numeric types, `number` and `integer`, where number includes both integer and floating-point numbers. An optional `format` keyword serves as a hint for the tools to use a specific numeric type.
> ✨ Add volumetric_weight_divisor_factor to Contract resource

- specification/parameters/query-filter-weight.json
This used to work before the latest release, so we're bringing back support for it.
> ♿️ Support decimal weight filter on service-rates endpoint

- specification/paths/Returns-v1-questions.json
- specification/schemas/return-questions/CreateReturnQuestionRequest.json
- specification/schemas/return-questions/PatchReturnQuestionRequest.json
- specification/schemas/return-questions/ReturnQuestion.json
- specification/schemas/return-questions/ReturnQuestionResponse.json
- 🔥 Removed `answer_type` attribute from ReturnQuestions resource.
> 🔥 Remove answer type from return questions

- specification/schemas/reports/Report.json
I encountered this error when selecting multiple countries in the Report form when selecting multiple countries.
~~In the back office code, we deliberately send a comma separated list of country codes to the API as filter. The API is also capable of handling this comma separated list of country codes.~~
~~The API Specification is where the problem lies. We have defined these inputs as being a CountryCode schema, but that does not support comma-separated entries.~~
~~Since the API supports this input, I believe our specification should allow it too.~~
The other filters all support arrays, so country codes should ha
- Changed `filters.recipient_address.country_code` and `filters.sender_address.country_code` attributes on Report schema to ~~support comma separated~~ country codes as array.
> :lady_beetle: Shipment report filter should have country code as array

- specification/paths/Returns-v1-return-methods.json
**Changes**
- add `[address_from][country_code]` and `[address_from][postal_code]` filters to `GET returns/v1/return-methods`
https://myparcelcombv.atlassian.net/browse/MP-6842
> :sparkles: Add address filters to `GET returns/v1/return-methods`

- specification/paths/Returns-v1-reports-count-report-entries.json
- specification/schemas/return-reports/ReturnReportFilters.json
Until now, return reports only supported date strings. 
These date strings are time zone dependent. 
When our back office sends the date filter to our API, it will do so in the timezone of the user, which might differ than the time zone of our API. It then will wrongly include or exclude results of a day earlier or later, depending on the timezone of the user. 
Adding support for timestamps, means that the user can always send a unix timestamp, which will always be in the UTC timezone, leading to us exactly knowing which of the returns to include in the report.
- ✨ Added support for numbers as date filters for return reports in order to respect timezone differences.
> :sparkles: Support timestamps for return report date filters.

- specification/paths/Returns-v1-return-methods.json
- specification/schemas/return-methods/ReturnMethod.json
- specification/schemas/return-methods/ReturnMethodResponse.json
Me, @yoerriwalstra and @M4tini discussed together with Matt that the postal codes filtering wouldn't be necessary now and is unlikely to ever be for returns. Although main motivation was because of the complicated queries that we had to do and the following preg_match. Therefore we looked for reasons not to implement it. 
After Lars is back we can discuss with him if postal code-based rates will be a thing for returns, and think of how to implement it in a simple way.
Merchants should be able to specify store-drop-off return methods to specific countries only. That's why the `country_codes` field was also added.
> 🔥  Removed postal code filter on return methods

- specification/schemas/reports/Report.json
- specification/schemas/return-reports/ReturnReportFilters.json
- Updated the Return report filters to specify ISO 8601 date format
- Updated Report date filter examples to correctly be in ISO 8601 format
> :recycle: Return report date filters should be ISO 8601 format.

- specification/schemas/return-reports/ReturnReportFilters.json
- The consumer country code filter on return reports should be of type array, to allow the user to select multiple countries when making a report.
- This is also in line with the reports for shipments, which also support selecting multiple.
> :lady_beetle: Country code filter should accept multiple country codes.

- specification/schemas/service-options/ServiceOption.json
- specification/schemas/service-options/ServiceOptionResponse.json
- specification/schemas/shipments/Shipment.json
We might have intended for `values_format` to be in the meta of service-options, but we implemented it as an attribute.
I think this meta is a mistake and most likely confused with `values`, which DO go in a meta (when used as relationship).
Since we also have implemented all other `..._format` json-schema properties as attributes, I think this is the way to go.
> FYI - our API and docs are already aligned + our app flattens everything onto a Model so that will work fine as well.
> 🚚 Move the ServiceOption `values_format` to its attributes where it belongs

- specification/paths.json
- specification/paths/Returns-v1-return-methods-resolve.json
- specification/paths/Returns-v1-return-methods.json
- specification/schemas/returns/ReturnRequest.json
I made some small changes compared to the implementation in the ticket:
- I decided not to include the entire create return request body just yet. That's because some things are too much, such as item attachments
- I did not add the `type` and `attributes`, not `relationships` in the input as they all seemed unnecessary. The request does not really have a type, because we are not creating a resource.
- I did not include the entire address object as only the country code is relevant at the moment. We can expand when needed with more fields
> ✨  Introduced new endpoint `POST /returns/v1/return-methods/resolve`

- specification/paths/Returns-v1-return-methods-resolve.json
- specification/paths/Returns-v1-return-methods.json
- specification/schemas/return-methods/ReturnMethodMeta.json
Some basic carrier and service fields like name, code and logo URL are always needed when the resolve return methods endpoint will be called. Therefore, it is not necessary to have them as relationship includes
> 👌🏻  Added carrier and service fields in return methods meta for easy access

- specification/paths/Services-service_id.json
- specification/paths/Services.json
- specification/schemas.json
- specification/schemas/services/Service.json
- specification/schemas/services/ServiceIncludes.json
- specification/schemas/zones/ZoneRelationship.json
This pull request introduces changes to enhance the service schema by adding zone relationship details. The most significant updates include modifications to the service JSON files to include new zone relationships and the addition of a new schema for `ZoneRelationship`.
* [`specification/paths/Services-service_id.json`](diffhunk://#diff-a8788e6a124502a0ec6f457f878217d80774cfcbcd60964592162063fac9216bL24-R24): Updated the `include` query parameter description to include `zone_from` and `zone_to` relationships.
* [`specification/paths/Services.json`](diffhunk://#diff-d7a65b63a6020b56dd36805a686d1a13d6ed4bb2ebcc6ce207e2b96128bb1b0eL128-R128): Updated the `include` query parameter description to include `zone_from` and `zone_to` relationships.
* …
> 👌🏻 🌍  Add zone relationships and includes to service endpoints

- specification/paths/Users.json
- specification/schemas/users/User.json
- specification/schemas/users/UserResponse.json
Changes:
- Added a `last_login` to the User schema
- Added the `filter[last_login_before]` to enable filtering users that have not been logged in for a while
- Exposed `last_login` in the UserResponse schema
Ticket: https://myparcelcombv.atlassian.net/browse/MP-7072
> MP-7072 Last login user attribute

- specification/paths/Users.json
- specification/schemas/users/User.json
- specification/schemas/users/UserResponse.json
Because of MyParcelCOM/api-specification#1148 I am creating this PR that reintroduces the reverted commits. 
The cause of this is because the original PR MyParcelCOM/api-specification#1147 was merged too early. Should always be at once with the api side of thing so that other pipelines are not impacted.
> Reintroduce "MP-7072 Last login user attribute""

- specification/schemas/users/UserResponse.json
Small bug with the addition `last_active` to the UserResponse required fields causing the schema to mismatch the API as it is actually not required.
> :lady_beetle: removed the last_active field from UserResponse.json required fields

- specification/schemas/files/DocumentType.json
Fix for: https://app.rollbar.com/a/myparcelcom/fix/item/api/9288
Our [carrier-specification](https://carrier-specification.myparcel.com/#tag/Manifests/paths/~1manifests/post) response is designed to return 3 file types: `label` + `printcode` + `manifest`
Because of that, our api-specification and API should also support these document types.
> 👽️ Add the manifest document type

- specification/paths/Returns-v1-returns.json
- specification/schemas/return-methods/ReturnMethod.json
- specification/schemas/returns/Return.json
- specification/schemas/returns/ReturnResponse.json
https://myparcelcombv.atlassian.net/browse/MP-7080
**TODO**
> :sparkles: Add `address` property to ReturnMethod and Return schemas

- specification/paths/Contracts-v1-templates.json
- specification/schemas/contract-templates/ContractTemplateResponse.json
- ✨ Added `countries_from` attribute to ContractTemplate schema.
- ✨ Added `filter[countries_from]` query param to the GET endpoint for contract templates
- https://myparcelcombv.atlassian.net/browse/MP-7122
I implore the reviewer to come up with an alternative name for this attribute if they can think of one.
> MP-7122 Add countries from attribute to contract template schema

- specification/paths/Marketplaces-v1-marketplaces-code-configure-shop-id.json
- specification/paths/Shops-shop_id-integrations-integration_id-configure.json
- Updated the allowed type for `value` property in configure integration endpoint to `string`, `number` or `boolean`.
- https://myparcelcombv.atlassian.net/browse/MP-7150
> :lady_beetle: MP-7150 Fixed allowed types for integration configure values.

- specification/paths/Hooks.json
I noticed that our back office expects to be able to include the owner of a hook in the request to fetch a hook.
We never built this include in the API though.
- 📝 Documented `owner` include on GET `/hooks` endpoint.
- https://github.com/MyParcelCOM/api/pull/3772
> :memo: Documented hook owner include

- specification/parameters.json
- specification/paths/SystemMessages.json
- specification/schemas/system-messages/SystemMessage.json
- We do not use the `country_code` attribute or the `country` filter when working with system messages.
- We do want to start using the `broker` filter when scoping the backoffice to a single broker.
- I also added a missing entry to the `parameters.json`.
> ♻️ Remove `country` filter and add `broker` filter to the system-messages endpoint

- specification/schemas/shops/Shop.json
- specification/schemas/shops/ShopResponse.json
The `Shop` should have not had the `additionalProperties=false`. It made the schema fail as now we have a required property `return_portal_url` which is part of the `ShopResponse`.
I used this as an opportunity to fix another inaccuracy which is that `return_portal_url` will always resolve to a valid string making `null` an invalid type. Fixed as well
NOTE: we went with @NickVries suggestions of utilizing `readOnly` [here](https://github.com/MyParcelCOM/api-specification/pull/1204#discussion_r2151872154)
> Bug + incorrect type fix

- specification/schemas/returns/ReturnResponse.json
- specification/schemas/returns/ReturnSimpleResponse.json
We need this to be able to make a return rule on the creation date of the order, if the outbound delivery date is unknown.
> ✨ Add `order_created_at` to meta of returns

- specification/paths/Onboarding-v1-invitations-invitation_id-onboard.json
- specification/paths/Onboarding-v1-invitations-invitation_id.json
- specification/paths/Onboarding-v1-invitations.json
- specification/tags.json
- This ticket is part of the refactor done in [this](https://github.com/MyParcelCOM/api/pull/3888) PR
Following a discussion with @yoan-myparcel we decided to rename the `Invitations` domain/namespace to `Onboarding` to be more concrete.
> [Hotfix] invitations tag changed to Onboarding

- specification/schemas/pickup-dropoff-locations/PickupDropoffLocationResponse.json
Almost none of our carriers use separate street numbers. The fact that this was tagged as required is kind of wild 🤯
> 🐛 PUDO location response should not list street_number as required

- specification/paths/Marketplaces-v1-integrations-code-configuration-shop-id.json
- specification/paths/Marketplaces-v1-integrations-code-configure-shop-id.json
- specification/paths/Wms-v1-integrations-code-configuration-shop-id.json
- specification/paths/Wms-v1-integrations-code-configure-shop-id.json
- specification/schemas.json
- specification/schemas/Configuration.json
- specification/schemas/ConfigurationSchemaProperty.json
- specification/schemas/ConfigurationValues.json
As mentioned in the ticket, I tried to make a recursive schema, in order to support validating the potentially nested schema properties, but Redoc would no longer render the UI if I used a self-referencing schema... This sucks, because a recursive schema is valid and we could use it for validation, but it is not compatible with the package that has to _render_ that schema... I (think) I get it from their point of view: how do you render a schema that potentially goes on infinitely? But it is bad for us that it limits us in our validating capacities.
I'm open to suggestions on what to do about it, other than just accept it. I have added a nested property with an explanatory comment that states that this is where nested properties should go and that they should adhere to the same schema, …
> :sparkles: Update configuration schema and paths
