MyParcelCOM/api-specification

specification/definitions.json, specification/definitions/Carrier.json, specification/definitions/Country.json, specification/definitions/Location.json, specification/definitions/Service.json, specification/definitions/ServiceGroup.json, specification/definitions/ServiceInsurance.json, specification/definitions/ServiceOption.json, specification/paths.json, specification/paths/Carriers-carrier_id.json, specification/paths/Carriers.json, specification/paths/Countries-country_id.json, specification/paths/Countries.json, specification/paths/Services-service_id.json, specification/paths/Services.json, specification/paths/ShipmentStatus.json, specification/tags.json
=> :memo: new spec for service, carrier and country

README.md, mp.sh
Even gelijk getrokken met de andere repo.
Nu nog kijken of het binnen Windows uit elkaar ploft. :sweat_smile:
=> :penguin: :apple: Fixed sed for both Mac and Linux.

specification/definitions/OpeningHours.json, specification/paths.json
=> :bug: enum ipv enumerate

specification/definitions.json, specification/definitions/Shipment.json, specification/definitions/Status.json, specification/definitions/Webhook.json, specification/definitions/WebhookSubscription.json, specification/paths.json, specification/paths/Shipments-shipment_id-Statuses.json, specification/paths/Shops-shop_id-WebhookSubscriptions-webhook_subscription_id.json, specification/paths/Shops-shop_id-WebhookSubscriptions.json, specification/paths/Statuses-status_id.json, specification/paths/Statuses.json, specification/tags.json
=> :construction: :memo: Status endpoints

specification/paths/Files.json, specification/paths/Shipments-shipment_id-Statuses.json, specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json, specification/paths/Shops-shop_id-WebhookSubscriptions-webhook_subscription_id.json, specification/paths/Shops-shop_id-WebhookSubscriptions.json, specification/paths/Shops-shop_id.json, specification/paths/Shops.json, specification/paths/Statuses-status_id.json, specification/paths/Statuses.json, specification/paths/Webhooks-webhook_id.json, specification/paths/Webhooks.json
=> :hammer: remove under cunstruction icons

specification/definitions/PickupDropoffLocation.json, specification/info.json, specification/paths/PasswordResets.json
=> :hammer: required password-reset email

specification/definitions/PasswordReset.json, specification/definitions/Shop.json, specification/paths/PasswordResets-password_reset_id.json, specification/paths/PasswordResets.json, specification/paths/Shops-shop_id.json, specification/relationships/Shop.json
=> :hammer: only require name for new shops

specification/definitions/Service.json, specification/info.json
=> ✨Added unstamped package_type

specification/definitions/Carrier.json, specification/definitions/Invitation.json, specification/definitions/Service.json, specification/definitions/Shipment.json, specification/definitions/Shop.json, specification/definitions/SystemMessage.json, specification/definitions/User.json, specification/definitions/Webhook.json, specification/info.json, specification/paths/Invitations.json
Will add customs to carrier spec when approved.
=> :sparkles: added customs to shipment

specification/paths/Services.json
=> :sparkles: added filter params to services endpoint

specification/definitions/Shipment.json, specification/info.json
https://myparcelcom.myjetbrains.com/youtrack/issue/API-81
=> :sparkles: Added tracking_code and tracking_url to shipment

specification/paths/Shipments.json, specification/paths/Shops-shop_id-WebhookSubscriptions.json, specification/paths/SystemMessages.json
[MP-159](https://myparcelcombv.atlassian.net/browse/MP-159)
=> MP-159 Remove references to multi delete

specification/definitions/Address.json, specification/definitions/Carrier.json, specification/definitions/Contract.json, specification/definitions/File.json, specification/definitions/Invitation.json, specification/definitions/PasswordReset.json, specification/definitions/PickupDropoffLocation.json, specification/definitions/Region.json, specification/definitions/Service.json, specification/definitions/ServiceGroup.json, specification/definitions/ServiceInsurance.json, specification/definitions/ServiceOption.json, specification/definitions/Shipment.json, specification/definitions/ShipmentEstimate.json, specification/definitions/ShipmentStatus.json, specification/definitions/Shop.json, specification/definitions/Status.json, specification/definitions/SystemMessage.json, specification/definitions/User.json, specification/definitions/Webhook.json, specification/definitions/WebhookSubscription.json
[MP-147](https://myparcelcombv.atlassian.net/browse/MP-147)
=> MP-147 read-only uuid required

specification/definitions/Service.json
[MP-194 Add handover_method to API spec](https://myparcelcombv.atlassian.net/browse/MP-194)
Part of [MP-191 Add handover_method to Services](https://myparcelcombv.atlassian.net/browse/MP-191)
=> MP-194 Add handover_method to API spec

specification/definitions/Address.json, specification/definitions/Carrier.json, specification/definitions/Contract.json, specification/definitions/File.json, specification/definitions/Invitation.json, specification/definitions/PasswordReset.json, specification/definitions/PickupDropoffLocation.json, specification/definitions/Region.json, specification/definitions/Service.json, specification/definitions/ServiceGroup.json, specification/definitions/ServiceInsurance.json, specification/definitions/ServiceOption.json, specification/definitions/Shipment.json, specification/definitions/ShipmentEstimate.json, specification/definitions/ShipmentStatus.json, specification/definitions/Shop.json, specification/definitions/Status.json, specification/definitions/SystemMessage.json, specification/definitions/User.json, specification/definitions/Webhook.json, specification/definitions/WebhookSubscription.json
Reverts MyParcelCOM/api-specification#115
=> Revert "MP-147 read-only uuid required"

specification/definitions/ServiceOption.json
[MP-201](https://myparcelcombv.atlassian.net/browse/MP-201)
Part of: [MP-197](https://myparcelcombv.atlassian.net/browse/MP-197)
=> MP-201 Update Api Spec with service option category and code

README.md
[MP-467](https://myparcelcombv.atlassian.net/browse/MP-467)
=> MP-467 Removed old references from the readme.

specification/definitions/PickupDropoffLocation.json, specification/includes/read-only-pudo-uuid.json
[MP-185](https://myparcelcombv.atlassian.net/browse/MP-185)
=> MP-185 Unique pudo ids

specification/paths/Shipments.json
Part of [MP-116](https://myparcelcombv.atlassian.net/browse/MP-116)
=> Updated get Shipments to include filtering on shop_id.

specification/definitions/Shipment.json
[MP-529](https://myparcelcombv.atlassian.net/browse/MP-529)
Part of [MP-512](https://myparcelcombv.atlassian.net/browse/MP-512)
=> MP-529 Move items out of customs

docker-compose.yml, mp/validate
[MP-420](https://myparcelcombv.atlassian.net/browse/MP-420)
=> MP-420 :sparkles: Replaced validator with new Open Api 3.0 validator.

specification/schemas/RegionCode.json
=> :recycle: updated regex from region code to also include empty string

README.md, docker-compose.yml, docker/json-bundler/Dockerfile, gulpfile.js, mp/bundle, specification/info.json, src/index.html, src/myparcelcom.css, src/myparcelcom.js
Check https://docs.myparcel.com/api-specification to see the css changes.
=> 💄 Feature/layout

specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json
[MP-603](https://myparcelcombv.atlassian.net/browse/MP-603)
Part of: [MP-602](https://myparcelcombv.atlassian.net/browse/MP-602)
=> MP-603 Service-contract.service include on shipment

specification/info.json, specification/paths/Shipments.json
MP-577 - [Jira](https://myparcelcombv.atlassian.net/browse/MP-577)
MP-580 - [Jira](https://myparcelcombv.atlassian.net/browse/MP-580)
=> MP-577/MP-580 Add tracking code and date to shipment search filter

specification/paths/Users.json
[MP-585](https://myparcelcombv.atlassian.net/browse/MP-585)
Part of: [MP-553](https://myparcelcombv.atlassian.net/browse/MP-553)
=> MP-585 Move meta out of data when posting user

specification/info.json, specification/schemas/Service.json
[MP-641](https://myparcelcombv.atlassian.net/browse/MP-641)
Part of: [MP-616](https://myparcelcombv.atlassian.net/browse/MP-616)
=> MP-641 Add delivery method to services

specification/schemas.json, specification/schemas/Customs.json, specification/schemas/InternationalShipment.json, specification/schemas/InvoiceCustoms.json
[MP-626](https://myparcelcombv.atlassian.net/browse/MP-626)
Part of: [MP-594](https://myparcelcombv.atlassian.net/browse/MP-594)
=> MP-626 Customs invoice number requirements

specification/schemas/ShipmentFilesRelationship.json
Links should be required instead
=> :bug: MP-680 Data should not be required on shipment file. 

specification/schemas/ServiceOption.json
[MP-657](https://myparcelcombv.atlassian.net/browse/MP-657)
Part of: [MP-654](https://myparcelcombv.atlassian.net/browse/MP-654)
=> MP-657 Change example for service-option code

specification/schemas/Shop.json
[MP-637](https://myparcelcombv.atlassian.net/browse/MP-637)
Part of: [MP-429](https://myparcelcombv.atlassian.net/browse/MP-429)
=> MP-637 Remove billing address from shop

specification/schemas/Organization.json, specification/schemas/Shop.json
Part of: [MP-639](https://myparcelcombv.atlassian.net/browse/MP-639)
=> Moved coc and iban property from shop to organization.

specification/parameters.json, specification/parameters/path-organization_id.json, specification/paths.json, specification/paths/Organizations-organization_id.json, specification/paths/Organizations.json, specification/schemas/Organization.json
[MP-780](https://myparcelcombv.atlassian.net/browse/MP-780)
=> MP-780 Add organization endpoints to api spec

specification/paths/SystemMessages-system_message_id.json, specification/paths/SystemMessages.json
Part of MP-763
https://myparcelcombv.atlassian.net/secure/RapidBoard.jspa?rapidView=1&modal=detail&selectedIssue=MP-763
=> Add experimental to system messages tags

specification/schemas/Carrier.json
**Changes**
- Added code property to carrier schema
- https://myparcelcombv.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=MP&modal=detail&selectedIssue=MP-783
=> Add slugified version of carrier name as `code`

specification/paths/CarrierContracts-carrier_contract_id.json, specification/paths/Carriers-carrier_id-CarrierContracts.json, specification/schemas/CarrierContract.json, specification/schemas/MinimalBroker.json
**Changes**
- Add `active` attribute to `CarrierContract`
- Add `status` attribute to `CarrierContract`
- Add `owner` relationship to `CarrierContract`
- Add `include` parameter to `CarrierContract` paths
- https://myparcelcombv.atlassian.net/browse/MP-630
=> Add owner status active properties to carrier contracts

specification/info.json, specification/paths/Organizations-organization_id.json, specification/paths/Organizations.json, specification/schemas/CombinedFile.json, specification/schemas/Organization.json
Part of: [MP-639](https://myparcelcombv.atlassian.net/browse/MP-639)
=> Add broker relationship to organization schema.

package-lock.json, package.json
=> ⬆️ updated swagger ui

specification/schemas/File.json
**Changes**
- Add `customs-declaration-form` to document type enum for file resource
=> :sparkles: Add customs-declaration-form to file document type enum

package.json, specification/info.json, specification/paths/Users.json
[MP-875](https://myparcelcombv.atlassian.net/browse/MP-875)
Part of: [MP-862](https://myparcelcombv.atlassian.net/browse/MP-862)
=> MP-875 Remove shop name from post user

package-lock.json, package.json, specification/info.json, specification/paths/Carriers-carrier_id-PickupDropoffLocations-country_code-postal_code.json, specification/schemas/PickupDropoffLocation.json
[MP-883](https://myparcelcombv.atlassian.net/browse/MP-883)
=> Added pudo categories and a filter for the corresponding endpoint.

package.json, specification/info.json, specification/paths/Organizations.json, specification/schemas/Organization.json
https://myparcelcombv.atlassian.net/browse/MP-864
=> ♻️ add meta with volume to organization post request

specification/info.json, specification/schemas/ServiceGroup.json
**Changes**
- Added max length, height, width and volume to service group schema.
=> MP-920 Added max dimension properties to service groups.

package.json, specification/info.json, specification/schemas/Address.json, specification/schemas/InternationalShipment.json, specification/schemas/Shipment.json
**Changes**
- Postal code is now required on ALL addresses.
- Some properties on addresses can now be patched to `null`
=> Fixed requirements on shipment addresses

package.json, specification/info.json, specification/paths/Services.json
**Changes**
- Added delivery method filter to services endpoint.
=> :sparkles: Added delivery method filter to service queries.

specification/schemas/InternationalShipment.json
**Changes**
- Removed SKU code from shipment items in shipment schema.
- https://myparcelcombv.atlassian.net/browse/MP-1141
=> MP-1141 Remove sku code from shipment.

specification/schemas/Region.json
**Changes**
- Added category to region resource
- https://myparcelcombv.atlassian.net/browse/MP-1175
=> Add category to region resource

package.json, specification/info.json, specification/schemas/PatchShop.json, specification/schemas/Shop.json
**Changes**
- Added required `website`attribute to shop schema.
=> MP-1180 Added required website attribute to shop schema.

src/myparcelcom.css
**Changes**
- Hid carrier contract endpoints and models
- Hid invitation endpoints and models
- Hid system message endpoints and models
- https://myparcelcombv.atlassian.net/browse/MP-1318
=> Hide carrier contract, combined file, invitation and system message endpoints and models

src/myparcelcom.css
**Changes**
- Removed experimental state from `/carrier-contracts` endpoints
- https://myparcelcombv.atlassian.net/browse/MP-1317
=> Remove experimental state from carrier-contracts endpoint

specification/schemas/ServiceGroup.json
**Changes**
- Made amount property of service group price non-required and nullable
- https://myparcelcombv.atlassian.net/browse/MP-1281
=> Make amount of service group price non-required and nullable

package.json, specification/info.json, specification/paths/PaymentIdentities-payment_identity_id.json, specification/schemas.json, specification/schemas/PatchPaymentIdentity.json
**Changes**
- Added PatchPaymentIdentity schema to specifically reflect which properties can be patched.
=> Patch Payment Identity Schema

specification/paths/Payments-payment_id.json, specification/paths/Payments.json, specification/schemas/Payment.json
**Changes**
- Added scopes
- Status required when posting payment
=> Payment fixes

specification/paths/ServiceContracts-service_contract_id.json, specification/paths/ServiceContracts.json, specification/paths/Services-service_id-ServiceContracts.json
https://myparcelcombv.atlassian.net/browse/MP-1394
=> Add service to include

specification/paths/PaymentIdentities-payment_identity_id.json, specification/paths/PaymentIdentities.json, specification/schemas/PatchPayment.json
- Added missing scope to payment identities.
- Limited payment patch attributes and relationships.
=> :recycle: patch payment schema

.env.dist, specification/info.json
**Changes**
- Removed `v1` from api host
- https://myparcelcombv.atlassian.net/browse/MP-1545
=> Remove /v1 from host

specification/paths/Services.json
https://myparcelcombv.atlassian.net/browse/MP-1525
No need to release.
=> :recycle: rename has_contract filter to has_active_contract

specification/examples/ShipmentResponse.json, specification/schemas/BaseShipment.json, specification/schemas/InternationalShipment.json, specification/schemas/Shipment.json
[MP-1527](https://myparcelcombv.atlassian.net/browse/MP-1527)
=> Removed shipment parent relationship.

specification/examples/ShipmentResponse.json, specification/schemas/InternationalShipment.json, specification/schemas/Shipment.json
[MP-1566](https://myparcelcombv.atlassian.net/browse/MP-1566)
=> Removed physical_properties_verified.

package.json, specification/info.json, specification/paths/CarrierContracts.json, specification/schemas/CarrierContract.json, specification/schemas/PatchCarrierContract.json
=> ✨ Updated carrier contract path to only allow patching of (in)active status

package.json, specification/info.json, specification/schemas.json, specification/schemas/Organization.json, specification/schemas/PatchOrganization.json
- https://myparcelcombv.atlassian.net/browse/MP-1521
New release for 0.24.0 required
=> Remove IBAN, payment-method, payment-term and renamed coc

package-lock.json, package.json, specification/info.json, specification/paths/Organizations.json, specification/paths/Shops.json, specification/paths/Users.json
- https://myparcelcombv.atlassian.net/browse/MP-1586
=> Add search to organisation shop and user

specification/paths.json, specification/paths/ServiceGroups.json, specification/schemas/ServiceGroup.json, specification/schemas/ServiceOptionsRelationship.json
Note that the resource has not been renamed yet.
- https://myparcelcombv.atlassian.net/browse/MP-1591
=> ♻️ Updated service-groups resource with new properties and relationships

package.json, specification/info.json, specification/parameters.json, specification/parameters/path-contract_id.json, specification/paths.json, specification/paths/Carriers-carrier_id-Contracts.json, specification/paths/Contracts-contract_id.json, specification/paths/Contracts.json, specification/paths/ServiceContracts-service_contract_id.json, specification/paths/ServiceContracts.json, specification/paths/Services-service_id-ServiceContracts.json, specification/schemas.json, specification/schemas/Contract.json, specification/schemas/ContractRelationship.json, specification/schemas/MinimalContract.json, specification/schemas/PatchContract.json, specification/schemas/ServiceContract.json, specification/schemas/ServiceContractsRelationship.json
**Changes**
- Renamed all references of carrier contract to contract.
- https://myparcelcombv.atlassian.net/browse/MP-1618 (subtask)
- https://myparcelcombv.atlassian.net/browse/MP-1590 (story)
=> MP-1618 rename carrier contracts to contracts

specification/schemas/ServiceRate.json
**Changes**
- Renamed a relationship on the ServiceRate schema.
=> Fixed the name of a relationship in service rate schema.

specification/paths/Regions.json
**Changes**
- Added postal code filter to regions endpoint
- https://myparcelcombv.atlassian.net/browse/MP-1682
=> Add postal code filter to regions endpoint

specification/paths/Services.json
**Changes**
- Added `address_from` and `address_to` filters to services endpoint
=> Add address filters to services endpoint

specification/paths/ServiceRates.json
**Changes**
- Added filters for service, contract and weight to GET /service-rates endpoint.
- https://myparcelcombv.atlassian.net/browse/MP-1701 (subtask)
- https://myparcelcombv.atlassian.net/browse/MP-1626 (story)
=> MP-1701 add service rates filters

specification/paths/Users.json
https://myparcelcombv.atlassian.net/browse/MP-1691
- Removed the user search filter because it has not be implemented.
=> :fire: removed user search filter

specification/schemas/Service.json
*Changes*
- Removed contracts relation from service resource
=> Remove contracts from service

package-lock.json, specification/paths/ServiceRates-service_rate_id.json, specification/paths/ServiceRates.json
https://myparcelcombv.atlassian.net/browse/MP-1744
=> :sparkles: includes on service-rate endpoints

specification/examples/PostShipmentRequest.json, specification/schemas/BaseShipmentItem.json, specification/schemas/InternationalShipment.json, specification/schemas/ShipmentItem.json
**Changes**
- Renamed nett_weight to item_weight
**Related issuess**
- https://myparcelcombv.atlassian.net/browse/MP-1771
=> Rename nett_weight to item_weight

package.json, specification/info.json, specification/schemas/Status.json
**Changes**
Status schema:
- Added level to required attributes.
- Changed the status code enum to reflect new proposal
- Added `in-progress` to levels enum.
- [MP-1820](https://myparcelcombv.atlassian.net/browse/MP-1820) (Subtask)
- [MP-1580](https://myparcelcombv.atlassian.net/browse/MP-1580) (Story)
=> MP-1820 Updated status schema code and level enums

specification/parameters.json, specification/parameters/path-client_id.json, specification/paths.json, specification/paths/Clients-client_id.json, specification/paths/Clients.json, specification/schemas.json, specification/schemas/Client.json, specification/schemas/MinimalClient.json, specification/schemas/UserRelationship.json
https://myparcelcombv.atlassian.net/browse/MP-1889
=> Add client resource and endpoints to spec

specification/schemas/Service.json
https://myparcelcombv.atlassian.net/browse/MP-1894
=> Add code to service resource

package-lock.json
No related issue.
- Ran `npm audit fix` to fix packages with vulnerabilities.
=> :lock: npm audit fix

specification/schemas/Error.json
- https://myparcelcombv.atlassian.net/browse/MP-1917
Tests Run, but says that its incomplete,  this was the output:
=> :pencil2: MP-1917 update details to detail

specification/paths/ServiceRates-service_rate_id.json, specification/schemas.json, specification/schemas/PatchServiceRate.json
- https://myparcelcombv.atlassian.net/browse/MP-1937
=> Add patch service-rate endpoint

specification/paths/Hooks-hook_id.json, specification/schemas.json, specification/schemas/PatchHook.json
**Changes**
- Added PATCH hooks endpoint
- https://myparcelcombv.atlassian.net/browse/MP-1971
=> Add patch hooks endpoint

specification/paths/Hooks-hook_id.json, specification/paths/Hooks.json
Only the `PATCH` endpoint had scopes. I added scopes to the other endpoints.
=> :lock: added scopes to hook endpoints

specification/info.json, specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json, specification/schemas/InternationalShipment.json, specification/schemas/Shipment.json
**IMPORTANT**
- Do not merge this until the rel
- https://myparcelcombv.atlassian.net/browse/MP-2004
=> MP-2004 Shipment contract and service optional

specification/paths/ServiceRates.json
- https://myparcelcombv.atlassian.net/browse/MP-1984
=> MP-1984 add API spec documentation entry

specification/info.json, specification/schemas/Shipment.json
=> 🐛 Allow shipment description to be null

package-lock.json, package.json, specification/schemas/HookAction.json
- https://myparcelcombv.atlassian.net/browse/MP-1804
=> Added object to hook action value type

specification/schemas/Client.json
- https://myparcelcombv.atlassian.net/browse/MP-1557
=> :recycle: added created_at to client resource

specification/info.json, specification/schemas/BasePhysicalProperties.json
[MP-2141](https://myparcelcombv.atlassian.net/browse/MP-2141)
=> Set minimum values for physical properties.

specification/info.json, specification/schemas/HookTrigger.json
**Changes** 
- Removed the required constraint from hook trigger predicate attribute since it did accept an empty array, and there are situations where a user would not want to have a predicate (e.g. when you want something to happen to EVERY created shipment).
=> 🔥 Removed required constraint from hook trigger predicate.

specification/info.json, specification/schemas/Status.json
- https://myparcelcombv.atlassian.net/browse/MP-2150
=> Update status enum values

specification/info.json, specification/schemas/InternationalShipment.json, specification/schemas/Shipment.json
- https://myparcelcombv.atlassian.net/browse/MP-1555
Not sure if I need to add something else...
Also the ticked mentions the relationship name should be `origin` but has a question mark. can we discuss that here? 
I'll implement whatever we decide later :)
=> [MP-1555] Add client origin meta to shipment

specification/paths.json, specification/paths/SuggestAddress.json
- https://myparcelcombv.atlassian.net/browse/MP-2175
=> MP-2175 Added /suggest-address RPC endpoint

specification/paths.json, specification/paths/SuggestAddress.json
- https://myparcelcombv.atlassian.net/browse/MP-2211
=> Moved RPC endpoint to bottom

docker-compose.yml, docker/json-bundler/Dockerfile, package-lock.json, package.json
- Updated node.
- Updated swagger-ui.
=> :arrow_up: updated packages

specification/info.json, specification/paths/Services.json
- https://myparcelcombv.atlassian.net/browse/MP-2165
=> Add code filter to service

specification/paths/SuggestAddress.json
- https://myparcelcombv.atlassian.net/browse/MP-2315
=> :sparkles: Added fields city, street_1 and renamed response.street_na

specification/info.json, specification/schemas/InternationalShipment.json, specification/schemas/Shipment.json
- https://myparcelcombv.atlassian.net/browse/MP-2318
=> Added channel attribute to shipment

.circleci/config.yml, .dockerignore, docker/build/Dockerfile, docker/build/default.conf, kube/deployment.template.yaml, kube/service.template.yaml, package-lock.json, package.json
**Changes**
- Added build of a docker image `myparcecom/api-specification`
- Added kubernetes deployment, service and ingress
=> 🐳 ☸ Dockerized and Kubernetized api-specification

specification/info.json, specification/schemas/Status.json
- https://myparcelcombv.atlassian.net/browse/MP-2369 (Subtask)
- https://myparcelcombv.atlassian.net/browse/MP-2270 (Story)
=> MP-2369 Added shipment-processing to status enum.

specification/info.json, specification/parameters.json, specification/parameters/path-hook-log_id.json, specification/paths.json, specification/paths/HookLogs-hook_log_id.json, specification/paths/Shipments.json, specification/paths/Users-user_id.json, specification/paths/Users.json, specification/schemas.json, specification/schemas/HookLog.json, specification/schemas/HookLogRelationship.json, specification/schemas/HookRelationship.json, specification/schemas/Shipment.json, src/myparcelcom.css
- https://myparcelcombv.atlassian.net/browse/MP-2307
=> Add hook logs

specification/info.json
=> Changed version

package-lock.json, package.json, src/myparcelcom.css, src/myparcelcom.js
- Fixed JavaScript issue on production.
- Updated layout to match the website.
=> MP-2404 - Fixed javascript errors

package-lock.json, specification/schemas.json, specification/schemas/Service.json, specification/schemas/ServiceRegion.json
- https://myparcelcombv.atlassian.net/browse/MP-2431 (Subtask)
- https://myparcelcombv.atlassian.net/browse/MP-2274 (Story)
=> MP-2431 Regions_to and regions_from attributes on service schema.

specification/paths/Services.json
- https://myparcelcombv.atlassian.net/browse/MP-2445
=> Added address to region code and address from region code

package-lock.json, package.json
Fixed security alert about `axios` package.
https://github.com/MyParcelCOM/api-specification/network/alert/package-lock.json/axios/open
=> ⬆️ updated packages

specification/schemas/Service.json
[Subtask: MP-2477](https://myparcelcombv.atlassian.net/browse/MP-2477)
[Story: MP-2411](https://myparcelcombv.atlassian.net/browse/MP-2411)
=> MP-2477 Added uses_volumetric_weight property to service schema.

specification/schemas/User.json
- https://myparcelcombv.atlassian.net/browse/MP-2543
=> Add locale to user

specification/paths/ServiceRates.json
- [MP-2556](https://myparcelcombv.atlassian.net/browse/MP-2556) (Subtask)
- [MP-2500](https://myparcelcombv.atlassian.net/browse/MP-2500) (Story)
=> MP-2556 Added volumetric weight filter for service-rates endpoint.

package-lock.json, specification/schemas/Shipment.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2570)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2306)
=> MP-2570 Added total_value to shipment schema.

package-lock.json, specification/schemas.json, specification/schemas/Hook.json, specification/schemas/HookAction.json, specification/schemas/HookActionTriggerWebhook.json, specification/schemas/HookActionUpdateResource.json, specification/schemas/PatchHook.json
- https://myparcelcombv.atlassian.net/browse/MP-2567
=> Add webhook functionality

specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json
- https://myparcelcombv.atlassian.net/browse/MP-2584
=> MP-2584 Label mime type on shipment endpoints.

specification/paths/Shipments.json, src/myparcelcom.css
https://myparcelcombv.atlassian.net/browse/MP-2587
=> :pencil: added shipment date filters

specification/parameters/header-files.json, specification/schemas/Carrier.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2598)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2559)
=> MP-2598 Label mime types on carrier response and file ZPL header.

package-lock.json, specification/schemas.json, specification/schemas/Hook.json, specification/schemas/HookAction.json, specification/schemas/HookActionSendResource.json, specification/schemas/PatchHook.json
Renamed `trigger-webhook` to `send-resource`.
=> ✏️ Rename trigger-webhook to send-resource

specification/schemas/HookActionSendResource.json, specification/schemas/HookActionUpdateResource.json
=> 🐛 Action values are now restricted by action type.

specification/schemas/HookActionSendResource.json, specification/schemas/HookActionUpdateResource.json
=> 🐛  Bugfix/restrict hook action values by action type

specification/schemas/HookActionSendResource.json, specification/schemas/Shipment.json
- https://myparcelcombv.atlassian.net/browse/MP-2637
=> Added parent relation to shipment

specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json, specification/schemas/Shipment.json, specification/schemas/Status.json
- https://myparcelcombv.atlassian.net/browse/MP-2663
**IMPORTANT**
- Merge together with API PR to prevent develop from breaking.
=> MP-2663 add sync active to shipments resource

specification/schemas/ServiceRegion.json
- https://myparcelcombv.atlassian.net/browse/MP-2687
=> :recycle: added postal_code regex to service regions

specification/paths/ServiceRates.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2693)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2655)
=> MP-2693 Added has_active_contract filter to get services endpoint.

specification/parameters.json, specification/parameters/path-integration_id.json, specification/paths.json, specification/paths/Integrations-integration_id.json, specification/paths/Integrations.json, specification/schemas.json, specification/schemas/Integration.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2697)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2666)
=> MP-2697 Add integrations to API spec

package-lock.json, root.json, specification/parameters.json, specification/parameters/path-shipment_surcharge_id.json, specification/paths.json, specification/paths/ShipmentSurcharges-shipment_surcharge_id.json, specification/paths/ShipmentSurcharges.json, specification/paths/Shipments-shipment_id-Surcharges-shipment_surcharge_id.json, specification/paths/Shipments-shipment_id-Surcharges.json, specification/schemas.json, specification/schemas/MinimalShipmentSurcharge.json, specification/schemas/PatchShipmentSurcharge.json, specification/schemas/ShipmentSurcharge.json
- https://myparcelcombv.atlassian.net/browse/MP-2700
- https://myparcelcombv.atlassian.net/browse/MP-2669
=> ✨ Added shipment surcharges to specification 

specification/schemas/PatchShipmentSurcharge.json
- https://myparcelcombv.atlassian.net/browse/MP-2735
=> 🐛 Disable shipment surcharge additional properties on patch 

specification/schemas/PatchShipmentSurcharge.json
- https://myparcelcombv.atlassian.net/browse/MP-2735
=> :bug: Disable shipment surcharge additional properties on patch

specification/paths.json, specification/paths/SynchronizeIntegration.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2728)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2691)
=> MP-2736 Added RPC endpoint for synchronizing with integrations.

specification/schemas/PatchShipmentSurcharge.json
- https://myparcelcombv.atlassian.net/browse/MP-2740
=> :bug: Removed additional properties restriction for patch shipment

specification/parameters/path-carrier_surcharge_id.json, specification/paths.json, specification/paths/CarrierSurcharges-carrier_surcharge_id.json, specification/paths/CarrierSurcharges.json, specification/schemas.json, specification/schemas/CarrierSurcharge.json, specification/schemas/MinimalCarrierSurcharge.json, specification/schemas/PatchCarrierSurcharge.json
- https://myparcelcombv.atlassian.net/browse/MP-2745
- Main story https://myparcelcombv.atlassian.net/browse/MP-2652
=> Added carrier-surcharges resource

package-lock.json, specification/schemas/Service.json
- https://myparcelcombv.atlassian.net/browse/MP-2755
=> Add information to services

specification/parameters.json, specification/parameters/path-liability_coverage_id.json, specification/paths.json, specification/paths/Contracts.json, specification/paths/LiabilityCoverage-liability_coverage_id.json, specification/schemas.json, specification/schemas/Contract.json, specification/schemas/LiabilityCoverage.json, specification/schemas/LiabilityCoveragesRelationship.json, specification/schemas/MinimalLiabilityCoverage.json
- https://myparcelcombv.atlassian.net/browse/MP-2761
=> Add liablility coverage

specification/parameters.json, specification/paths.json, specification/paths/CarrierSurcharges-carrier_surcharge_id.json, specification/paths/CarrierSurcharges.json, specification/schemas.json, specification/schemas/CarrierSurcharge.json, specification/schemas/PatchCarrierSurcharge.json
- https://myparcelcombv.atlassian.net/browse/MP-2745
=> ♻️ Proper required attributes for carrier surcharges

specification/paths/Contracts.json, specification/schemas/Contract.json
- https://myparcelcombv.atlassian.net/browse/MP-2761
=> Changed line to underscore in relation

package-lock.json, specification/paths/Integrations-integration_id.json, specification/paths/Shops-shop_id-relationships-integrations.json
- `credentials` are not required for patch.
- `meta` is not required for delete.
=> :recycle: proper required attributes for shop integrations

specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json, specification/paths/Shops-shop_id.json, specification/paths/Shops.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2785)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2294)
=> MP-2785 Added organization include on the shops endpoint.

specification/schemas/Integration.json
- https://myparcelcombv.atlassian.net/browse/MP-2782
=> Add logo and readme url to integrations

specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json, specification/schemas.json, specification/schemas/LiabilityCoverageRelationship.json, specification/schemas/PatchShipment.json, specification/schemas/Shipment.json
**Changes**
- Add `liability_coverage` relationship to shipment resource.
- Sort shipment relationships and includes alphabetically.
- https://myparcelcombv.atlassian.net/browse/MP-1765
=> MP-1765 ✨ Add liability coverage to shipment

specification/schemas/Organization.json, specification/schemas/PatchOrganization.json
- https://myparcelcombv.atlassian.net/browse/MP-2817
- Main story https://myparcelcombv.atlassian.net/browse/MP-2747
=> Added EORI number to Organization schema

specification/schemas/PatchShipment.json, specification/schemas/Shipment.json
- https://myparcelcombv.atlassian.net/browse/MP-2853
=> Add shipment consolidation relation to shipments

package-lock.json, package.json, specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json
- https://myparcelcombv.atlassian.net/browse/MP-2878
=> ✨ Add service_code meta to shipment post/patch

specification/paths/Shipments.json
- https://myparcelcombv.atlassian.net/browse/MP-2916
=> MP-2916 Added country code filters to the shipment get endpoint.

specification/paths/SystemMessages.json, specification/schemas/PatchSystemMessage.json, specification/schemas/SystemMessage.json
**Changes**
- Added new field `country_code` to SystemMessage schema
- Added `filter[country_code]` to `GET /system-messages` path
**Jira**
- Main ticket: https://myparcelcombv.atlassian.net/browse/MP-2829 
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-2919
=> ✨ Added country code field to SystemMessage schema + filter to GET /system-messages

specification/paths/SystemMessages.json
**Changes**
- Renamed the country_code filter to country
- Now the filter is more abstract and includes system-wide messages too
=> 🎨 Abstracting the system messages country filter 

specification/schemas/PatchSystemMessage.json, specification/schemas/SystemMessage.json
https://myparcelcombv.atlassian.net/browse/MP-2937
=> MP-2937 ♻️ Allow system message country_code to be null

specification/schemas/Status.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2938)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2538)
=> MP-2938 Shipment-returned-to-sender status to status schema.

package-lock.json, package.json, specification/schemas/PatchShipment.json, specification/schemas/Shipment.json
https://myparcelcombv.atlassian.net/browse/MP-2576
=> MP-2576 ✏️ Changed channel example

specification/schemas/HookActionUpdateResource.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2881)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2862)
=> MP-2881 Hook action value converter

specification/schemas/Shipment.json
- Related issue: https://myparcelcombv.atlassian.net/browse/MP-3036
=> Add recipient_tax_id to shipment

specification/schemas/PatchShipment.json
- Related issue: https://myparcelcombv.atlassian.net/browse/MP-3036
Added recipient_tax_id also to patch
=> Added recipient_tax_id also to patch

specification/info.json, specification/parameters/path-postal_code.json, specification/schemas/Address.json
- related issue: https://myparcelcombv.atlassian.net/browse/MP-3049
=> Remove postal code requirements

specification/paths/Hooks.json
**Changes**
- Add owner filter to hooks
- https://myparcelcombv.atlassian.net/browse/MP-2715
=> Add owner filter to hooks

specification/info.json, specification/paths.json, specification/paths/CarrierSurcharges-carrier_surcharge_id.json, specification/paths/Clients-client_id.json, specification/paths/Contracts-contract_id.json, specification/paths/Hooks-hook_id.json, specification/paths/ShipmentSurcharges-shipment_surcharge_id.json, specification/paths/Shipments-shipment_id.json, specification/paths/SystemMessages-system_message_id.json, specification/paths/VoidShipment.json
https://myparcelcombv.atlassian.net/browse/MP-2914
- `/void-shipment` RPC endpoint accepting shipment_id in post data.
- Returning 204 on success and 423 on error.
=> ✨ Void shipment endpoint

package-lock.json, specification/paths.json, specification/paths/Organizations-organization_id-contracts.json, specification/paths/Organizations-organization_id-relationships-contracts.json, specification/paths/Shops-shop_id-relationships-integrations.json, specification/schemas.json, specification/schemas/ContractsRelationship.json
- https://myparcelcombv.atlassian.net/browse/MP-3107
=> MP-3107 Added endpoints for organization contract endpoints.

specification/paths/UpdateShipmentStatus.json
https://myparcelcombv.atlassian.net/browse/MP-3209
=> MP-3209 ♻️ Repurpose update-shipment-status endpoint

specification/paths/Shipments.json, specification/schemas/PatchShipment.json, specification/schemas/Shipment.json
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-3211)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-3155)
=> MP-3211 Added customer reference to shipment attributes.

specification/paths/UpdateShipmentStatus.json
https://myparcelcombv.atlassian.net/browse/MP-3240
=> MP-3240 Update-shipment-status endpoint synchronous

package-lock.json, package.json, specification/schemas/Organization.json, specification/schemas/PatchOrganization.json
https://myparcelcombv.atlassian.net/browse/MP-3226
=> MP-3226 ✨ Added voec_number to organization

specification/paths/Statuses-status_id.json, specification/paths/Statuses.json, specification/schemas/Integration.json
https://myparcelcombv.atlassian.net/browse/MP-3241
=> MP-3241 ♻️ Allow for integrations without credentials

package-lock.json, specification/schemas/HookActionUpdateResource.json
Subtask: https://myparcelcombv.atlassian.net/browse/MP-3295
Story: https://myparcelcombv.atlassian.net/browse/MP-3250
=> MP-3295 Allow array as hook action value value.

specification/paths/Users.json
https://myparcelcombv.atlassian.net/browse/MP-3232
=> MP-3232 💥 broker_id instead of client_id in user meta

specification/paths/Shipments.json
Added new filter for description field (exact matches)
=> ✨ Introduced exact description filter

specification/schemas/Contract.json
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3358
- Story: https://myparcelcombv.atlassian.net/browse/MP-3304
=> MP-3358 Added template relationship to contract schema. ✨

specification/paths.json, specification/paths/ExportShipments.json, specification/paths/Shipments.json
Added new endpoint for downloading shipments in CSV details
=> RPC /export-shipments

specification/schemas/Shipment.json
- Added group of verified attributes: price and physical_properties
- Made all physical_properties optional
https://myparcelcombv.atlassian.net/browse/MP-3389
=> ✨ Introduced verified attributes

package-lock.json, specification/paths/Analytics-on-time-delivery.json
Spec part of https://github.com/MyParcelCOM/api/pull/1410
=> 👌 Added service_code filtering for on-time-delivery stats

.dockerignore, .gitignore, .validaterc, README.md, docker-compose.yml, mp/bundle, mp/validate, root.json, specification/info.json, specification/paths/Invoices-invoice_id.json, specification/paths/Invoices.json, specification/paths/LiabilityCoverage-liability_coverage_id.json, specification/paths/PaymentIdentities.json, specification/schemas/Analytics.json, specification/schemas/Hook.json, specification/schemas/HookAction.json, specification/schemas/LiabilityCoveragesRelationship.json, specification/schemas/PatchHook.json, specification/schemas/PickupDropoffLocation.json, src/index.html, src/myparcelcom.css, src/myparcelcom.js
- Changed links from http to https.
- Removed useless chown while bundling.
- Reworded scope descriptions.
- Removed redundant `LiabilityCoverage` properties.
- Removed invalid `LiabilityCoveragesRelationship` links.
- Updated outdated `HookAction` component and use it for `Hooks`.
- Moved styles from HTML to CSS file.
- Used JavaScript to open external links in a new tab.
- Used redoc options to modify rendering process.
- Repaired `mp validate` using `IBM/openapi-validator`.
=> ⚡️ Various improvements

specification/schemas/RegionCode.json
https://myparcelcombv.atlassian.net/browse/MP-3484
- This field is deprecated and the validation blocks Shopify shipments.
- The API has no limitations and the database field is 255 characters.
=> MP-3484 🔥 Removed region code validation

specification/paths/Brokers.json, specification/paths/Carriers.json, specification/schemas/Broker.json
https://myparcelcombv.atlassian.net/browse/MP-3366
=> MP-3366 ✨ Added broker style

README.md, composer.json, root.json, specification/paths/Users-user_id.json, specification/paths/Users.json, specification/schemas/PatchUser.json
- Added `users.manage` scope.
- Added `filter[search]` to get users endpoint.
- Added `status` to patch user endpoint.
=> MP-3280 ✨ Added users.manage scope

specification/schemas/PatchShipment.json, specification/schemas/Shipment.json
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3510
- Story: https://myparcelcombv.atlassian.net/browse/MP-3390
=> MP-3510 Added tags to the shipment schema.

specification/paths.json, specification/paths/Users-user_id-relationships-scopes.json, specification/schemas.json, specification/schemas/MinimalScope.json, specification/schemas/ScopesRelationship.json, specification/schemas/Shipment.json
https://myparcelcombv.atlassian.net/browse/MP-3544
=> MP-3544 ✨ User scopes relationships endpoint

specification/parameters.json, specification/parameters/path-scope_id.json, specification/paths.json, specification/paths/Scopes-scope_id.json, specification/paths/Scopes.json, specification/schemas.json, specification/schemas/Scope.json, specification/tags.json
https://myparcelcombv.atlassian.net/browse/MP-3537
=> MP-3537 ✨ Scope endpoints

specification/paths/Hooks.json
- https://myparcelcombv.atlassian.net/browse/MP-3583
=> MP-3583 Added hook action_type filter.

specification/paths/Users-user_id-relationships-scopes.json
https://myparcelcombv.atlassian.net/browse/MP-3632
We forgot about this little feature...
=> ♻️ Added meta to user scopes relationship endpoint

specification/info.json, specification/paths/Organizations-organization_id-relationships-contracts.json, specification/paths/Users-user_id-relationships-scopes.json, specification/schemas/ScopesRelationship.json
https://myparcelcombv.atlassian.net/browse/MP-3536
I removed some duplicate user-scopes code in the process.
=> MP-3645 ✨ Post user scopes endpoint

specification/paths/Users-user_id-relationships-scopes.json, specification/schemas/Broker.json, specification/schemas/Shipment.json
https://myparcelcombv.atlassian.net/browse/MP-3647
- Added broker attributes
- `logo_url`
- `favicon_url`
- `support_url`
- `contact_url`
- Added note that `broker.member` scope cannot be removed from a user.
=> ✨ Added broker url attributes

specification/info.json, specification/schemas/BaseShipmentItem.json, specification/schemas/ShipmentItem.json
https://myparcelcombv.atlassian.net/browse/MP-3668
=> MP-3673 ✨ Added image_url to shipment item

specification/paths/Shops.json
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3676
- Story: https://myparcelcombv.atlassian.net/browse/MP-3466
=> MP-3676 Added organization filter on shops endpoint.

specification/schemas/PatchShipment.json
https://myparcelcombv.atlassian.net/browse/MP-3507
=> MP-3507 ♻️ Nullable contract and service

specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3715
- Story: https://myparcelcombv.atlassian.net/browse/MP-3590
=> MP-3715 Added consolidation_shipment to shipment includes.

specification/paths/Shipments.json
This change will allow "included" property in create shipment responses
=> Allowing additional properties for create shipment responses

specification/paths.json, specification/paths/Analytics-volume-carriers.json, specification/paths/Analytics-volume.json
Introduced new endpoint for volumes per carrier. All shipment filters are applicable.
=> MP-3739 Added new analytics endpoint for carrier volumes

specification/parameters.json, specification/parameters/path-report_id.json, specification/paths.json, specification/paths/Reports-report_id.json, specification/paths/Reports.json, specification/schemas.json, specification/schemas/Report.json, specification/schemas/ReportIncludes.json, specification/schemas/ReportResource.json, specification/schemas/ReportResponse.json, specification/tags.json
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3756
- Story: https://myparcelcombv.atlassian.net/browse/MP-3492
=> MP-3756 Reports endpoints

specification/paths.json, specification/paths/RegisterShipment.json, specification/paths/RegisteredShipments.json, src/myparcelcom.js
https://myparcelcombv.atlassian.net/browse/MP-3770
Leave the branch, I need to make a merge PR to develop.
=> ✨ Registered shipments endpoint

specification/parameters.json, specification/parameters/query-shipments-filter-carrier.json, specification/parameters/query-shipments-filter-created_at-date_from.json, specification/parameters/query-shipments-filter-created_at-date_to.json, specification/parameters/query-shipments-filter-current_status_code.json, specification/parameters/query-shipments-filter-customer_reference.json, specification/parameters/query-shipments-filter-date_from.json, specification/parameters/query-shipments-filter-date_to.json, specification/parameters/query-shipments-filter-description.json, specification/parameters/query-shipments-filter-organization.json, specification/parameters/query-shipments-filter-recipient_address-country_code.json, specification/parameters/query-shipments-filter-register_at-date_from.json, specification/parameters/query-shipments-filter-register_at-date_to.json, specification/parameters/query-shipments-filter-search.json, specification/parameters/query-shipments-filter-sender_address-country_code.json, specification/parameters/query-shipments-filter-service_code.json, specification/parameters/query-shipments-filter-shop.json, specification/parameters/query-shipments-include.json, specification/paths/Analytics-volume.json, specification/paths/ExportShipments.json, specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json
- Added new range filters for created_at and register_at
- Deprecated old date range filters
- Refactored shipment filter parameters into separate json files
=> Introduced filter[created_at] and filter[register_at] date range filters for shipments

specification/schemas.json, specification/schemas/BaseAddress.json, specification/schemas/StateCode.json
https://myparcelcombv.atlassian.net/browse/MP-3678
- Added `state_code` to all addresses.
- Removed deprecated `region_code`.
=> MP-3811 ✨ Added state_code to address schema

specification/schemas/Shipment.json
https://myparcelcombv.atlassian.net/browse/MP-3748
=> ✨ Added sender_tax_number to shipments resource

specification/paths/RegisteredShipments.json, specification/schemas.json, specification/schemas/DocumentType.json, specification/schemas/File.json, specification/schemas/FileFormat.json
Added a meta array of files (including contents) to the response of POST /registered-shipments
=> Added meta with file contents to registered-shipments response

specification/schemas.json, specification/schemas/Organization.json, specification/schemas/TaxIdentificationNumber.json
- Introduced new schema TaxIdentificationNumber
- Used with Organization resource
=> ✨ Added tax identification numbers to Organizations schema

specification/schemas/PatchOrganization.json
Patch was impossible due to missing tax_identification_numbers field
=> Added missing tax_identification_numbers in PatchOrganization

specification/paths/UpdateShipmentStatus.json, specification/schemas.json, specification/schemas/CarrierStatus.json, specification/schemas/ShipmentStatus.json
- https://myparcelcombv.atlassian.net/browse/MP-3917
=> MP-3917 Manually update carrier status

specification/schemas/BaseCustoms.json
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3922
- Story: https://myparcelcombv.atlassian.net/browse/MP-3773
=> MP-3922 Added shipping value to the customs schema.

.circleci/config.yml, specification/paths.json, specification/paths/Shops-shop_id-integrations-integration_id-shipments.json
Added new endpoint for fetching shipments from integration
=> Introduced GET /shops/{shop_id}/integrations/{integration_id}/shipments endpoint

specification/schemas/HookActionSendResource.json
- https://myparcelcombv.atlassian.net/browse/MP-3831
=> MP-3831 Added retry properties to HookActionSendResource schema.

specification/schemas/HookLog.json
- https://myparcelcombv.atlassian.net/browse/MP-3980
=> MP-3980 Hook name in hook log

kube/deployment.template.yaml
=> ☸️ 🐳 Pod Disruption Budgets

mp/up, root.json, specification/paths/Contracts-contract_id.json, specification/paths/Contracts.json, specification/paths/Files-file_id.json, specification/paths/HookLogs-hook_log_id.json, specification/paths/Hooks-hook_id-logs.json, specification/paths/Hooks-hook_id.json, specification/paths/Hooks.json, specification/paths/LiabilityCoverage-liability_coverage_id.json, specification/paths/Reports-report_id-Files-file_id.json, specification/paths/Reports-report_id.json, specification/paths/Reports.json, specification/paths/Shipments-shipment_id-Files.json, specification/paths/Shipments-shipment_id-Statuses-shipment_status_id.json, specification/paths/Shipments-shipment_id-Statuses.json, specification/paths/Shipments-shipment_id-Surcharges-shipment_surcharge_id.json, specification/paths/Shipments-shipment_id-Surcharges.json, specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json, specification/paths/Shops-shop_id-integrations-integration_id-shipments.json, specification/paths/Shops-shop_id-integrations.json, specification/paths/Shops-shop_id-relationships-integrations.json, specification/paths/Shops-shop_id.json, specification/paths/Shops.json
https://myparcelcombv.atlassian.net/browse/MP-3908
I decided to give `shipments.view` on GET shipments + all GET endpoints to retrieve Shipment relationship resources.
=> MP-4038 ✨ Introduce shipments.view scope

specification/paths/Carriers.json, specification/schemas/Carrier.json
MP-2799 - Service filter should only show carriers available to organization
MP-4013 - Get the logo from a carrier resource instead of basing it on the carrier name
=> MP-2799 MP-4013 ✨ Added logo_url to carrier resource

specification/schemas/ServiceRate.json
https://myparcelcombv.atlassian.net/browse/MP-3918
=> ✨ Added fuel_surcharge to ServiceRate resource

specification/paths.json, specification/paths/ExportLoginAttempts.json, src/myparcelcom.js
- Introduced `GET /export-login-attempts` for retrieving CSV with login attempts
=> ✨ Added endpoint for exporting login attempt logs

root.json, specification/paths/ExportLoginAttempts.json
Experimental scope will not be enough. We want to expose logs information only to specific users.
=> ✨ Introduced new scope

specification/paths/RegisteredShipments.json, specification/paths/Shipments.json, specification/schemas/Carrier.json
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-4198
- Story https://myparcelcombv.atlassian.net/browse/MP-4162
=> MP-4198 Label size for carriers and shipment request.

specification/paths.json, specification/paths/RegisterMultiColliShipment.json
https://myparcelcombv.atlassian.net/browse/MP-3613
- I decided to name the RPC endpoint `/register-multi-colli-shipment` because that's what it does.
- I copied the attribute requirements from the POST shipments endpoint.
=> MP-4203 ✨ register-multi-colli-shipment endpoint

specification/paths.json, specification/paths/Brokers.json, specification/paths/Carriers.json, specification/paths/Contracts.json, specification/paths/Enterprises.json, specification/paths/Hooks.json, specification/paths/Invoices.json, specification/paths/Organizations.json, specification/paths/ServiceOptions.json, specification/paths/ServiceRates.json, specification/paths/Services.json, specification/paths/Shipments.json, specification/paths/Shops.json
https://myparcelcombv.atlassian.net/browse/MP-4310
- Added `GET /enterprises` endpoint.
- Removed `for your API client` from menu item titles - this is implied by `available` and already stated in the description.
=> ✨ GET /enterprises

specification/paths/Brokers-broker_id.json, specification/paths/Enterprises-enterprise_id.json, specification/paths/Enterprises.json
https://myparcelcombv.atlassian.net/browse/MP-4320
=> MP-4320 🐛 Broker relationship should not be patched

specification/schemas/TaxIdentificationNumber.json
- Introduced `vat` and `ioss` types
=> ✨ Introduced new tax identification number types vat and ioss

specification/schemas/BaseShipmentItem.json
**changes**
- Added vat_percentage with a min and max value.
**links**
- https://myparcelcombv.atlassian.net/browse/MP-4282
=> 🌌 MP-4284 added the vat_percentage field to the shipment item

specification/paths.json, specification/paths/Brokers-broker_id-carriers.json, specification/paths/Brokers-broker_id-relationships-carriers.json, specification/paths/Carriers-carrier_id-Contracts.json, specification/paths/Hooks-hook_id-logs.json, specification/paths/Organizations-organization_id-contracts.json, specification/schemas.json, specification/schemas/CarriersRelationship.json
- Added the new broker - carrier relationship endpoint to the api-spec
- https://myparcelcombv.atlassian.net/browse/MP-3746
=> MP-3746 🔩 Added the new endpoint to the api-spec

specification/paths/Brokers-broker_id-carriers.json
- Removed properties that aren't needed on this endpoint.
=> 👾 MP-3746 update broker carrier relationship 

specification/paths.json, specification/paths/CalculateLandedCosts.json
- Added rpc endpoint for landed cost calculation
=> 🛬 MP-4386 Updated api spec with RPC endpoint for landed cost calculation

specification/paths.json, specification/paths/CalculateLandedCosts.json, specification/paths/Suggest-hscode.json
- Added hs code suggestion endpoint to the api spec
- https://myparcelcombv.atlassian.net/browse/MP-4385
=> 🛬 MP-4385 Added hscode suggestion rpc endpoint to api spec

specification/paths.json, specification/paths/ConsolidateShipments.json
=> 🤏 MP-4487 Added consolidate shipments rpc endpoint to spec

specification/paths/RegisterMultiColliShipment.json
=> MP-4514 Added service option ids to the multicolli endpoint

specification/paths/RegisterMultiColliShipment.json
- Updated the service option ids on the multicolli endpoint to hold objects for service option values instead of just an array of service option ids.
=> 🦺 MP 4541 api-spec service options values

specification/schemas/Shipment.json
Part of https://myparcelcombv.atlassian.net/browse/MP-4549
=> MP-4555 ♻️ Added multi_colli_shipment to shipment resource

specification/schemas/Integration.json
Integrations have two distinct features:
- they can work with the shipment import tool
- they can have an OAuth2 authentication flow
Both of these indicate UI usages of the integrations. To avoid two new boolean field in the specification I decided to introduce tags.
=> ✨ Introduced integration tags

specification/schemas/Manifest.json
- Added contract relationship to manifest schema
- Added readOnly meta errors property.
- https://myparcelcombv.atlassian.net/browse/MP-4623
=> MP-4623 Manifest Contract and errors

specification/paths/GetDynamicServiceRates.json
Also added the correct value to the request body since that is what the middleware does (or actually doesnt do)
=> Dynamic service rate accept header

specification/parameters/query-filter-created_at-date_from.json, specification/parameters/query-filter-created_at-date_to.json
- Added timestamps as possible option for date filters on the GET /shipment endpoint.
- https://myparcelcombv.atlassian.net/browse/MP-4686
=> MP-4686 Timestamps in date filters

specification/paths.json, specification/paths/CountReportEntries.json, specification/schemas.json, specification/schemas/BaseReport.json, specification/schemas/Report.json
- Added new RPC endpoint for counting report entries
- Introduced BaseReport schema that does not have the "name" attribute
=> Introduced new RPC endpoint /count-report-entries

root.json, specification/parameters.json, specification/parameters/path-zone_id.json, specification/paths.json, specification/paths/Zones-zone_id.json, specification/paths/Zones.json, specification/schemas.json, specification/schemas/Zone.json, specification/schemas/ZoneResource.json, specification/schemas/ZoneResponse.json, specification/tags.json
- Introduced the zone resource and its respective endpoints
=> 🇮🇴🇹🇫🇵🇸 MP-4709 Zones

specification/paths/GetDynamicServiceRates.json
- introduced shop relationship since its needed when requesting a service rate's dynamic values.
=> Dynamic service rate relationSHOP

specification/paths/Zones-zone_id.json, specification/paths/Zones.json
- Added DELETE `/zone/:zoneId` endpoint
- Added country_code filter to the GET `/zones` endpoint.
=> ✨ Added delete zone endpoint.

README.md, docker-compose.yml, docker/build/Dockerfile, docker/json-bundler/Dockerfile, specification/paths/Manifests.json, specification/schemas/BaseCustoms.json, specification/schemas/BaseShipmentItem.json, specification/schemas/Broker.json, specification/schemas/CombinedFile.json, specification/schemas/Contract.json, specification/schemas/Day.json, specification/schemas/DocumentType.json, specification/schemas/HookTrigger.json, specification/schemas/Language.json, specification/schemas/Manifest.json, specification/schemas/PickupDropoffLocation.json, specification/schemas/Region.json, specification/schemas/Service.json, specification/schemas/ShipmentsRelationship.json, specification/schemas/SystemMessage.json, specification/schemas/TaxIdentificationNumber.json, specification/schemas/User.json
- Updated Node.
- Updated Redoc.
- Removed unnecessary examples (the first enum element is the defauilt example).
=> 🐳 Updated Node and Redoc

specification/parameters/query-shipments-include.json, specification/schemas.json, specification/schemas/ManifestRelationship.json, specification/schemas/Shipment.json
- Added manifest relationship to shipment schema.
- Added ManifestRelationship schema.
- [MP-4756](https://myparcelcombv.atlassian.net/browse/MP-4756): Subtask
- [MP-4703](https://myparcelcombv.atlassian.net/browse/MP-4703): Story
=> MP-4756 ✨ Added manifest relationship to shipment schema.

specification/paths/CombinedFiles-combined_file_id.json, specification/paths/CombinedFiles.json, specification/paths/ConsolidateShipments.json
Subtask of https://myparcelcombv.atlassian.net/browse/MP-4563
=> MP-4770 ♻️ Replace the experimental scope with shipments.manage

specification/schemas/Service.json
- added `strict_consolidation` property to the service
- https://myparcelcombv.atlassian.net/browse/MP-4767
=> 🙅‍♂️ MP-4767 Added strict_consolidation field to the service

specification/schemas.json, specification/schemas/FinalMileCarrier.json, specification/schemas/Shipment.json
- Introduced readonly optional object on shipment `final_mile_carrier` on the shipment resource
=> 🔗 MP-4823 Added final mile carrier

specification/paths/Services.json
- Added strict consolidation filter on services 
- https://myparcelcombv.atlassian.net/browse/MP-4838
=> 🙅‍♀️ MP-4838 Added strict consolidation filter

specification/paths/RegisteredShipments.json
- Expanded the registered shipments object with a collection object in the meta attribute.
- https://myparcelcombv.atlassian.net/browse/MP-4895
=> ⚡MP-4895 Added collection meta object

specification/paths/Carriers-carrier_id-PickupDropoffLocations-country_code-postal_code.json, specification/paths/Carriers-carrier_id-PickupDropoffLocations-latitude-longitude.json
👌 PUDO contract is not longer a filter
=> 👌 PUDO contract is not longer a filter

specification/parameters.json, specification/parameters/query-shipments-filter-carrier_status-category.json, specification/paths/Shipments.json
- Introduced a new filter for status categories on shipments
=> Added status category filter

specification/paths.json, specification/paths/GetCarrierStatusCategories.json
https://myparcelcombv.atlassian.net/browse/MP-4263
=> MP-4263 ✨ RPC endpoint to retrieve carrier status categories

specification/paths/RegisterMultiColliShipment.json, specification/paths/RegisteredShipments.json, specification/paths/Shipments.json
Add the idempotency functionality to the `/register-multi-colli-shipment` endpoint.
=> ♻️ Idempotency for /register-multi-colli-shipment endpoint

specification/paths/Collections-collection_id.json, specification/paths/Collections.json, specification/schemas/Collection.json
- Added register attribute on collections
- Somehow the preview request on the right shows the register property on the patch endpoint but the main pane in the middle doesn't.
=> patchable collections

specification/info.json, specification/paths/Shops-shop_id-integrations-integration_id-shipments.json
Integrations are not always able to provide the data removed in this PR.
=> 🔥 Remove data requirements from integration shipments

specification/schemas/Carrier.json
This reverts commit 5ddcc39dca98646e1bbba22a6e6658f2d586fab8, reversing
changes made to 00e02c7776855804226262c25208eac2e4d2a2db.
=> Revert #699

specification/schemas/Carrier.json
This reverts commit 5c836c52b0f2b388ec804d82ab43fc83e0f14c64, reversing
changes made to 5ddcc39dca98646e1bbba22a6e6658f2d586fab8.
=> Revert #700

specification/paths/RegisterMultiColliShipment.json
- Added customs info to the multicolli endpoint.
- https://myparcelcombv.atlassian.net/browse/MP-5008
- https://myparcelcombv.atlassian.net/browse/MP-5032
=> MP-5032 Added customs info to the multicolli endpoint.

specification/paths.json, specification/paths/ExportRatesTemplate.json
- https://myparcelcombv.atlassian.net/browse/MP-3455
=> [Api-spec] Export rates template

specification/schemas/Carrier.json
- Added new object to the carrier resource, the object holds collection related options.
- https://myparcelcombv.atlassian.net/browse/MP-5024
=> MP-5024 Added collection options on carrier resource

specification/paths.json, specification/paths/MultiColliShipments.json, specification/paths/RegisterMultiColliShipment.json, specification/paths/RegisteredShipments.json
https://myparcelcombv.atlassian.net/browse/MP-5041
---
- Deprecate multi-colli RPC endpoint.
- Create POST /multi-colli-shipments endpoint with colli in meta.
=> ♻️ Restructure multi-colli POST endpoint

specification/schemas/TaxIdentificationNumber.json
=> 🇦🇺 [Api-specification] MP-4968 added gst to tax number enum

specification/paths/Carriers-carrier_id-PickupDropoffLocations-country_code-postal_code.json, specification/paths/Carriers-carrier_id-PickupDropoffLocations-latitude-longitude.json, specification/schemas/PickupDropoffLocation.json
Added also the first feature "print-label-in-store"
=> ✨ Introduced PUDO features

specification/schemas/Organization.json
Needed before we merge https://github.com/MyParcelCOM/api/pull/2433
=> 🔥 Remove organization language and currency

specification/paths/Organizations-organization_id.json, specification/paths/Organizations.json, specification/schemas.json, specification/schemas/OrganizationMeta.json
https://myparcelcombv.atlassian.net/browse/MP-5168
---
This will add to the organization post and patch request:
```
"meta": {
"logo": {
"mime_type": "image/png",
"contents": "base64 encoded image data"
}
}
```
=> ✨ Organization meta with logo

specification/schemas.json, specification/schemas/RatesImport.json, specification/schemas/ServiceRateImport.json
- https://myparcelcombv.atlassian.net/browse/MP-5099
=> MP-5099 Added service rate import schema.

specification/paths.json, specification/paths/CreateManifestForCollection.json
- https://myparcelcombv.atlassian.net/browse/MP-5178
=> :sparkles: Introduced create manifest for collection endpoint.

specification/paths/RateImports.json, specification/schemas/RatesImport.json, specification/schemas/RatesImportResponse.json
- Introduced post endpoint
- Removed `sheet_contents` from the attributes in the resource itself since we don't return it to the user.
=> :rat: [api-spec] Post RatesImport

specification/paths/RateImports.json, specification/schemas/RatesImport.json, specification/schemas/RatesImportResponse.json
- Added filters
- Added includes
=> :rat: [api-spec] Rate imports filter and includes 

specification/paths/Collections.json, specification/schemas/Collection.json, specification/schemas/CollectionResponse.json
https://myparcelcombv.atlassian.net/browse/MP-5239
---
- Deprecate collections `name`.
- Add optional `description` to collections.
=> ♻️ Deprecate collections name in favor of description

specification/paths/Collections.json, specification/schemas/CollectionResponse.json
Made the following fields optional:
- address
- collection_time
- relationships.contract
=> [api-spec] MP-5171 untracked collections

specification/parameters.json, specification/paths/Carriers-carrier_id-CollectionTimeSlots.json
https://myparcelcombv.atlassian.net/browse/MP-5334
---
- Added optional `service_code` parameter to collection-time-slots request.
- Fixed alphabetical order of paths file contents.
=> 👽️ Added service_code to collection-time-slots request

.env.dist, docker/build/entrypoint.sh, mp/bundle, specification/info.json
Show the generated `RELEASE_VERSION` from the environment config.
=> 🔖 Display current version number in specification

specification/paths/Collections-collection_id.json
=> 🐛 Hide empty collection relationships when all are read-only

specification/paths/Users-user_id.json, specification/paths/Users.json
https://myparcelcombv.atlassian.net/browse/MP-5348
---
- All user endpoints should require `users.manage`.
- `POST /users` should return a resource instead of an empty response.
=> ♻️ Require users.manage and return user on post

specification/paths/Shops.json, specification/schemas/ShopResponse.json
https://myparcelcombv.atlassian.net/browse/MP-4718
=> ♻️ Require addresses on all shops

specification/paths/Collections-collection_id.json
- Introduced new optional relationship
https://myparcelcombv.atlassian.net/browse/MP-5172
=> MP-5347 patch Collection status to colllection-collected

specification/paths/Organizations.json, specification/paths/Shops.json, specification/schemas/Organization.json, specification/schemas/Shop.json
=> Revert "🚀 Update staging"

specification/paths.json, specification/paths/AddShipmentsToCollection.json, specification/schemas/Carrier.json
- Introduced new boolean property on the carrier to indicate if registered shipments can be added to a collection
- Introduced new rpc endpoint to bulk add shipments to a collection
=> MP-5488 Add registered shipments to a collection

specification/paths/Organizations-organization_id.json, specification/paths/Shops-shop_id.json
https://myparcelcombv.atlassian.net/browse/MP-5320
=> :sparkles: [api-spec] Added delete for shops and organizations

specification/parameters.json, specification/parameters/path-collection_schedule_id.json, specification/paths.json, specification/paths/CollectionSchedules-collection_schedule_id.json, specification/paths/CollectionSchedules.json, specification/schemas.json, specification/schemas/CollectionSchedule.json, specification/schemas/CollectionScheduleResource.json, specification/tags.json
- Added CollectionSchedule schema
- Added GET, GET by id, POST and DELETE endpoints for collection schedules.
- https://myparcelcombv.atlassian.net/browse/MP-5146
=> MP-5146 collection schedules

specification/schemas/BaseShipmentItem.json
- Added `is_preferential_origin` attribute to ShipmentItem schema.
- https://myparcelcombv.atlassian.net/browse/MP-5481
=> MP-5481 Preferential origin

specification/paths/RateImports.json
https://myparcelcombv.atlassian.net/browse/MP-5588
=> :beetle: Mark sheet_contents as optional

specification/paths/Collections.json
- Added shipments relationship to POST collections 
- Added register property to POST collections
- https://myparcelcombv.atlassian.net/browse/MP-5722
=> :necktie: Added shipments relationship and register attribute to post collections

specification/paths/Manifests.json, specification/schemas/Manifest.json, specification/schemas/ManifestIncludes.json, specification/schemas/ManifestResponse.json
https://myparcelcombv.atlassian.net/browse/MP-5319
=> Changed shop relationship to owner relationship for Manifests

specification/paths/Manifests.json, specification/schemas/Manifest.json, specification/schemas/ManifestIncludes.json, specification/schemas/ManifestResponse.json
Reverts MyParcelCOM/api-specification#811
=> Revert "Revert "Changed shop relationship to owner relationship for Manifests""

mp.sh
Similar to https://github.com/MyParcelCOM/carrier-specification/pull/219.
Although API project will create the proxynet, I am adding the creation here too as a precaution.
=> 🐞 Make sure proxynet is created

specification/schemas/ReturnResource.json
- Removed required id because else the post call requiring an id
=> :beetle: Removed required id because else the post call requiring an id

.env.dist, docker/build/entrypoint.sh, mp/bundle, specification/schemas/Shipment.json, specification/schemas/ShipmentResponse.json
https://myparcelcombv.atlassian.net/browse/MP-5314
=> MP-5314 - Added tracking page url to shipment responses

specification/paths/Integrations-integration_id.json, specification/paths/Integrations.json, specification/paths/Shops-shop_id-integrations.json, specification/paths/Shops-shop_id-relationships-integrations.json, specification/schemas.json, specification/schemas/Integration.json, specification/schemas/IntegrationResource.json, specification/schemas/IntegrationResponse.json, specification/schemas/IntegrationsRelationship.json
https://myparcelcombv.atlassian.net/browse/MP-6000
---
- Convert integrations to the new resource structure.
- Added `settings_format` to integrations.
- Added `settings` to shop-integration relationships.
=> ✨ Integrations with settings

docker-compose.yml, docker/build/Dockerfile, docker/json-bundler/Dockerfile, specification/schemas/Broker.json, specification/schemas/CollectionScheduleTime.json, specification/schemas/PickupDropoffLocation.json
- Update to node 18 image.
- Fixed the support_url example.
=> ⬆️ Updated to node 20

specification/parameters.json
- Correctly register the `query-shipments-filter-channel` schema as parameter in `parameters.json`.
=> :lady_beetle: Register channel query filter schema.

docker-compose.yml, docker/json-bundler/Dockerfile
=> ⚡️ Use slim image for the json-bundler

specification/schemas/ReturnResponse.json
- Made the shop and status relationships of returns required
=> :recycle: Made shop and status relationships of return required.

specification/schemas/Integration.json, specification/schemas/IntegrationResponse.json
- Introduced 2 new attributes to determine if an integration is providing outbound shipments and/or single order fetching
https://myparcelcombv.atlassian.net/browse/MP-5983
=> :heavy_plus_sign: Introduced returns attributes on integrations

specification/paths/Returns-v1-returns-return_id.json, specification/paths/Returns-v1-shops-shop_id-orders-reference-email.json, specification/schemas.json, specification/schemas/BaseShipmentItem.json, specification/schemas/ItemFeature.json, specification/schemas/Order.json, specification/schemas/OrderItem.json, specification/schemas/OrderResource.json, specification/schemas/OrderResponse.json, specification/schemas/ReturnItem.json, specification/schemas/Weight.json
https://myparcelcombv.atlassian.net/browse/MP-5979
---
- Added `item_price` and `features` to return/order items.
- Grouped the two item weight and weight unit attributes into one `item_weight` attribute.
- Restructured the order resource and introduced `OrderResponse`
=> 🏷️ Return order price and features

specification/schemas/IntegrationResponse.json
- Make properties required
- This should be merged after the API PR gets merged (so we won't get any pipeline failures)
=> 👔 Make the new integration properties required

specification/paths/Returns-v1-returns.json
=> :beetle: Fixed returns pagination urls

specification/parameters.json, specification/parameters/path-return_method_id.json, specification/parameters/query-filter-service.json, specification/paths.json, specification/paths/Returns-v1-return-methods-return_method_id.json, specification/paths/Returns-v1-return-methods.json, specification/paths/ServiceRates.json, specification/schemas.json, specification/schemas/ReturnMethod.json, specification/schemas/ReturnMethodIncludes.json, specification/schemas/ReturnMethodResource.json, specification/schemas/ReturnMethodResponse.json, specification/tags.json, src/myparcelcom.js
- Introduced return methods resource
- Hide it from production
=> :sparkles: Introduced return methods

specification/schemas/Integration.json
https://myparcelcombv.atlassian.net/browse/MP-6037
---
Introduced an optional `connect_url` attribute to the Integration resource.
=> 🔗 Added connect_url to integrations

specification/paths/Returns-v1-return-methods-return_method_id.json, specification/schemas/ReturnMethodIncludes.json
https://myparcelcombv.atlassian.net/browse/MP-6036
---
The get-by-id endpoint should have the same includes as the get-all endpoint.
=> ♻️ Added includes to the GET return method by ID endpoint

specification/paths.json, specification/paths/Payments-v1-providers-mollie-authorization.json, specification/tags.json, src/myparcelcom.js
=> MP-6063 :sparkles: [api-spec] Introduced payment authorization for mollie

specification/schemas/Shop.json
- Introduced new property on a shop to indicate whether it has a connection with Mollie
- https://myparcelcombv.atlassian.net/browse/MP-5795
=> :sparkles: Added mollie_connected to shop

specification/paths.json, specification/paths/DownloadRatesTemplate.json, specification/paths/RequestRatesTemplate.json
Related Jira Issue: https://myparcelcombv.atlassian.net/browse/MP-5988
=> :wrench: update export-rates-template spec to new format: request-rates-template and download-rates-template

specification/paths/Shops.json
This filter will enable finding exact matches by shop name.
=> ✨ Added filter[name] on GET /shops

specification/schemas/Return.json
- Introduced optional shipment relationship
- Made the other relationships required.
=> :sparkles: Introduced optional shipment relationship on returns

specification/parameters.json, specification/parameters/path-return_reason_id.json, specification/parameters/query-filter-tags.json, specification/paths.json, specification/paths/Returns-v1-reasons-return_reason_id.json, specification/paths/Returns-v1-reasons.json, specification/paths/Returns-v1-shops-shop_id-reasons-return_reason_id.json, specification/paths/Returns-v1-shops-shop_id-reasons.json, specification/schemas.json, specification/schemas/ReturnReason.json, specification/schemas/ReturnReasonIncludes.json, specification/schemas/ReturnReasonResource.json, specification/schemas/ReturnReasonResponse.json, specification/tags.json, src/myparcelcom.js
- Introduced return reason resource
- Introduced shops-return reasons to attach a reason to a shop
- https://myparcelcombv.atlassian.net/browse/MP-5756
=> :sparkles: [api-spec] Return Reasons

specification/parameters.json, specification/parameters/query-filter-location_type.json, specification/paths/Carriers-carrier_id-PickupDropoffLocations-country_code-postal_code.json, specification/paths/Carriers-carrier_id-PickupDropoffLocations-latitude-longitude.json, specification/schemas/PickupDropoffLocation.json
https://myparcelcombv.atlassian.net/browse/MP-5890
=> 🏢 Added more office location types to PUDO

specification/paths/Returns-v1-shops-shop_id-reasons.json
- Added the correct request body for the post shop reasons endpoint
=> :lipstick: Fix POST shop reasons endpoint

root.json, specification/paths/Carriers-carrier_id.json, specification/paths/Carriers.json, specification/paths/Contracts-contract_id.json, specification/paths/Contracts.json, specification/paths/Integrations-integration_id.json, specification/paths/Integrations.json, specification/paths/Organizations-organization_id.json, specification/paths/Organizations.json, specification/paths/Services-service_id.json, specification/paths/Services.json, specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json, specification/paths/Shops-shop_id.json, specification/paths/Shops.json, specification/paths/SystemMessages-system_message_id.json, specification/paths/SystemMessages.json, specification/paths/Users-user_id.json
Specify missing scopes on endpoints that require them.
=> 💡 Specify missing scopes

specification/parameters.json, specification/parameters/query-filter-broker.json, specification/paths/Analytics-on-time-delivery.json, specification/paths/Analytics-volume.json, specification/paths/CarrierSurcharges.json, specification/paths/CollectionSchedules.json, specification/paths/Hooks.json, specification/paths/ServiceRates.json, specification/paths/Services.json, specification/paths/Shops.json
https://myparcelcombv.atlassian.net/browse/MP-5867
---
- Added broker filter on analytics endpoints.
- Use query filter parameter reference for existing components.
=> ⌛ Broker filter on analytics endpoints

specification/paths/Files-file_id.json, specification/paths/Shipments-shipment_id-Files.json, specification/paths/Shipments-shipment_id-Statuses-shipment_status_id.json, specification/paths/Shipments-shipment_id-Statuses.json, specification/paths/Shipments-shipment_id.json, specification/paths/Shipments.json
https://myparcelcombv.atlassian.net/browse/MP-6107
---
=> 🚪 `returns.manage` should be able to GET shipments, statuses and files

specification/paths/PasswordResets.json
This will overwrite the change in https://github.com/MyParcelCOM/api-specification/pull/921 and together they will result in this diff:
=> 👔 Password resets need the unique username instead of the email

specification/paths/Returns-v1-reasons.json, specification/schemas/ReturnReason.json, specification/schemas/ReturnReasonResponse.json
https://myparcelcombv.atlassian.net/browse/MP-6143
=> ✨ Return reasons can accept or require comments

specification/schemas/ReturnReason.json, specification/schemas/ReturnReasonResponse.json
- Added `code` property to ReturnReason schema and ReturnReasonResponse.
- https://myparcelcombv.atlassian.net/browse/MP-6163
- https://myparcelcombv.atlassian.net/browse/MP-6140
=> MP-6163 Return reason code

specification/schemas/ReturnReasonResponse.json
It's messing up other branches that have no API implementation yet.
=> :rewind: Make return reason code optional.

specification/paths/Returns-v1-returns.json
=> :mag: add search filter to /returns/v1/returns endpoint

specification/schemas/Integration.json, specification/schemas/IntegrationResponse.json
See https://myparcelcombv.atlassian.net/browse/MP-6201
=> :sparkles: Introduced creates_client flag

specification/schemas/Status.json
- Added missing `returns` to the enum for Status resource_type.
=> :lady_beetle: Added returns as resource type on Status schema.

specification/schemas.json, specification/schemas/HookAction.json, specification/schemas/HookActionApproveReturn.json, specification/schemas/HookActionRejectReturn.json
**Related Jira issue**
https://myparcelcombv.atlassian.net/browse/MP-6213
=> :sparkles: add new hook action types

specification/parameters.json, specification/parameters/query-filter-weight.json, specification/paths/Returns-v1-return-methods.json, specification/paths/ServiceRates.json, specification/schemas.json, specification/schemas/ReturnMethod.json, specification/schemas/ReturnMethodMeta.json
=> :sparkles: Introduced weight filter and price meta on return method

specification/paths/Manifests.json
https://myparcelcombv.atlassian.net/browse/MP-5899
=> ♻️ Support update_shipment_statuses meta when creating manifests

specification/paths/Returns-v1-returns.json, specification/schemas/ReturnItem.json, specification/schemas/ReturnResponse.json
**Related Jira issue**
https://myparcelcombv.atlassian.net/browse/MP-6256
=> :sparkles: add comment and attachments to return item reason

specification/parameters.json, specification/parameters/path-payment_id.json, specification/parameters/query-hmac.json, specification/paths.json, specification/paths/Returns-v1-returns-return_id-payment-checkout-url-payment_id.json, specification/paths/Returns-v1-returns-return_id-payment-link-payment_id.json, specification/schemas.json, specification/schemas/HookAction.json, specification/schemas/HookActionRequestPayment.json, specification/schemas/ReturnResponse.json
Alongside the new hook action, I also added the endpoint that will generate the mollie checkout URL once visited.
=> :sparkles: Added new hook action for requesting payments + checkout URL jump route

specification/schemas/ReturnMethod.json
- Added `name` property to the ReturnMethod schema
=> :sparkles: Added the name attribute to the ReturnMethod schema.

specification/paths/Integrations.json
- introduced tag filter
- https://myparcelcombv.atlassian.net/browse/MP-6243
=> :sparkles: Introduced tag filter on integrations

specification/paths/Shops-shop_id-integrations.json
- Introduced tag filter on `/shops/{shop}/integrations`
=> :sparkles: Introduced tag filter on `/shops/{shop}/integrations`

specification/parameters.json, specification/parameters/query-filter-date_from.json, specification/parameters/query-filter-date_to.json, specification/paths.json, specification/paths/Returns-v1-analytics-approved.json, specification/paths/Returns-v1-returns.json, specification/schemas.json, specification/schemas/ReturnAnalytics.json, specification/tags.json
- Added created_at filters on get returns 
- Added new endpoint for getting approved returns histogram
=> ✨  Added endpoint for getting histogram of approved returns

specification/paths.json, specification/paths/Payments-v1-providers-code-connect.json, specification/paths/Payments-v1-providers-code-disconnect.json, specification/paths/Payments-v1-providers.json, specification/schemas.json, specification/schemas/payment-providers/PaymentProvider.json, specification/schemas/payment-providers/PaymentProviderResource.json, specification/schemas/payment-providers/PaymentProviderResponse.json, specification/tags.json
- `/payments/v1/providers?shop_id={shop_id}`
- `/payments/v1/providers/{code}/connect`
- `/payments/v1/providers/{code}/disconnect`
=> ✨  Payment providers

specification/paths/Payments-v1-providers-code-connect.json, specification/paths/Payments-v1-providers.json, specification/schemas/payment-providers/PaymentProviderResponse.json
- Add additional error responses for payment provider connect endpoint
- Changed behavior of shop_id when getting providers
=> 👌🏻 Payment providers - QA feedback

specification/paths.json, specification/paths/Returns-v1-returns-return_id-request-recovery-shipment.json, specification/schemas/return-methods/ReturnMethod.json
https://myparcelcombv.atlassian.net/browse/MP-6352
---
- Introduce a `recovery_contract` and `recovery_service` on a ReturnMethod.
- Create an endpoint to request a recovery shipment for a return.
=> ❤️‍🩹 Request a recovery shipment for a return

root.json
- Added scopes for collections.
- Removed experimental scope.
- Sort alphabetically.
=> ✏️ Update list of scopes

specification/schemas/shipments/Shipment.json
https://myparcelcombv.atlassian.net/browse/MP-4554
=> 🔥 Removed the parent relationship from shipments

specification/paths/Returns-v1-reasons-return_reason_id.json, specification/schemas.json, specification/schemas/return-reasons/UpdateReturnReason.json
Note: this feels dumb, to make a new schema with 1 less property. Wouldn't mind looking into a more elegant solution
=> :hammer: add UpdateReturnReason schema

specification/paths/Shops.json, specification/schemas/shops/Shop.json
- Added `domain` property to the `return` branding property on shops.
- https://myparcelcombv.atlassian.net/browse/MP-6367
=> MP-6403 Added domain to the return branding of shops

specification/paths.json, specification/paths/Collections-collection_id-Files-file_id.json
https://myparcelcombv.atlassian.net/browse/MP-6444
=> :sparkles: add specification to for GET /collections/{collection_id}/files/{file_id}

specification/parameters.json, specification/parameters/header-accept-language.json, specification/paths/Returns-v1-reasons-return_reason_id.json, specification/paths/Returns-v1-reasons.json, specification/paths/Returns-v1-shops-shop_id-reasons.json, specification/schemas.json, specification/schemas/return-reasons/CreateReturnReason.json, specification/schemas/return-reasons/ReturnReason.json, specification/schemas/return-reasons/ReturnReasonManagementDescription.json, specification/schemas/return-reasons/ShopReturnReason.json, specification/schemas/return-reasons/ShopReturnReasonResponse.json
https://myparcelcombv.atlassian.net/browse/MP-6471
=> :sparkles: update ReturnReason schemas to include possible description object

specification/parameters.json, specification/parameters/path-invitation_id.json, specification/paths.json, specification/paths/Onboarding-v1-invitations-invitation_id.json, specification/paths/Onboarding-v1-invitations.json, specification/schemas.json, specification/schemas/invitations/Invitation.json, specification/schemas/invitations/InvitationIncludes.json, specification/schemas/invitations/InvitationResource.json, specification/schemas/invitations/InvitationResponse.json, specification/tags.json
- https://myparcelcombv.atlassian.net/browse/MP-6448
=> :sparkles: Introduced invitations resource

specification/paths.json, specification/paths/Onboarding-v1-invitations-invitation_id-onboard.json, specification/paths/Onboarding-v1-invitations.json, specification/schemas.json, specification/schemas/invitations/InvitationRequest.json
=> :wrench: Onboard a user

specification/paths/Returns-v1-shops-shop_id-orders-reference-email.json
https://myparcelcombv.atlassian.net/browse/MP-6538
=> :sparkles: [api-spec] Introduced new exception for 3rd party orders

specification/paths/Zones-zone_id.json, specification/paths/Zones.json
What you POST is what you GET.
=> 🔒️ Allow zones.manage to retrieve zones

specification/schemas/shops/Shop.json
https://myparcelcombv.atlassian.net/browse/MP-6514
---
Make nullable.
=> 🐛 Shop return domain should be nullable

specification/parameters/header-accept-language.json, specification/schemas/locales/LocaleEnum.json
https://myparcelcombv.atlassian.net/browse/MP-6549
=> :globe_with_meridians: Add values to LocaleEnum: `es-ES`, `fr-FR`, `pl-PL`

specification/schemas/shops/Shop.json, specification/schemas/shops/ShopResponse.json
https://myparcelcombv.atlassian.net/browse/MP-6559
=> :ghost: add hide_customer_reference and hide_sender_address attributes

specification/paths/Shops-shop_id-relationships-integrations.json, specification/schemas/integrations/Integration.json
+ :sparkles: Added possible 200 OK response to marketplace integration connect endpoint
=> 🔥  Deprecated marketplace integrations connect_url

specification/schemas/returns/ReturnResponse.json, specification/schemas/returns/ReturnSimpleResponse.json, specification/schemas/statuses/Status.json
=> :wrench: [api-spec] outbound shipment delivered at

specification/parameters.json, specification/parameters/query-filter-search-name.json, specification/paths/Organizations.json, specification/paths/Shops.json
- ✨ Introduced `filter[search.name]` on shops and organizations get endpoints.
- https://myparcelcombv.atlassian.net/browse/MP-6590
- https://myparcelcombv.atlassian.net/browse/MP-6086
=> MP-6590 🔍  Added search.name filter to shop and organization endpoints.

specification/schemas.json, specification/schemas/hooks/HookAction.json, specification/schemas/hooks/HookActionSetReturnDeadlinePassed.json
https://myparcelcombv.atlassian.net/browse/MP-6598
=> :sparkles: add HookAction set-return-deadline-passed

specification/schemas/locales/LocaleEnum.json
https://myparcelcombv.atlassian.net/browse/MP-6528
---
Make Greek.
=> 🇬🇷 Greek language

root.json, specification/paths/Returns-v1-shops-shop_id-reasons.json
=> 🧱 Fix incorrect json structure

docker-compose.yml, docker/build/Dockerfile, docker/json-bundler/Dockerfile
https://nodejs.org/en/about/previous-releases
=> 🔧 Update containers to node 22

specification/paths/Brokers.json, specification/schemas/brokers/Broker.json
https://myparcelcombv.atlassian.net/browse/MP-6734
=> 🚑️ Post brokers without specifying a domain

specification/schemas.json, specification/schemas/return-orders/BaseOrderItem.json, specification/schemas/return-orders/DemoOrder.json, specification/schemas/return-orders/DemoOrderResponse.json, specification/schemas/return-orders/OrderItem.json, specification/schemas/return-orders/OrderItemBase.json
+ ✏️  Added description to demo order item SKU
Demo orders can generate their own order item IDs
=> 👌🏻  Removed demo order item IDs

specification/schemas/service-rates/ServiceRate.json
- ✨ Added oversize surcharge to service rate schema
- https://myparcelcombv.atlassian.net/browse/MP-6760
=> :sparkles: MP-6760 Oversize charge on ServiceRates

specification/schemas/shipments/BaseCustoms.json
- 📝 Updated incoterm description to mention that it is required for certain content_types only.
- https://myparcelcombv.atlassian.net/browse/MP-6788
=> 📝 MP-6788 Updated incoterm description

specification/schemas/returns/ReturnSimpleResponse.json, specification/schemas/statuses/Status.json
=> [api-spec] :sparkles: Introduced new status shipment-returning-to-sender

specification/paths.json, specification/paths/Returns-v1-shops-shop_id-reasons-return_reason_id-questions-return_question_id.json, specification/paths/Returns-v1-shops-shop_id-reasons-return_reason_id-questions.json
https://myparcelcombv.atlassian.net/browse/MP-6822
=> :sparkles: Add endpoints to link and unlink question to shop return reason

.github/workflows/ci.yml
- Updated outdated github actions
=> :bricks: Maintenance actions update

specification/schemas/ImageMeta.json, specification/schemas/organizations/Organization.json, specification/schemas/organizations/TaxIdentificationNumber.json
Enforce the non-nullable strings on `organizations` to not be empty.
=> 👮 Reject empty string when required

specification/paths/Returns-v1-returns-return_id.json, specification/paths/Returns-v1-returns.json, specification/schemas.json, specification/schemas/return-orders/ItemReasonQuestion.json, specification/schemas/returns/GetReturnItem.json, specification/schemas/returns/PostReturnItem.json
=> :sparkles: Introduced questions on return.item.reason

src/myparcelcom.js
=> ✨ Show the shipment surcharge endpoints

specification/paths/ShipmentSurcharges.json, specification/schemas/shipment-surcharges/ShipmentSurchargeResponse.json
=> 🏷️ Require the name on shipment-surcharges

specification/parameters.json, specification/parameters/path-contract_template_id.json, specification/paths.json, specification/paths/Contracts-v1-templates-contract_template_id.json, specification/paths/Contracts-v1-templates.json, specification/schemas.json, specification/schemas/contract-templates/ContractTemplate.json, specification/schemas/contract-templates/ContractTemplateIncludes.json, specification/schemas/contract-templates/ContractTemplateResource.json, specification/schemas/contract-templates/ContractTemplateResponse.json, specification/tags.json, src/myparcelcom.js
https://myparcelcombv.atlassian.net/browse/MP-6893
---
- Make get-all.
- Make post.
- I decided to also make get-one and delete.
=> ✨ Contract templates

specification/paths.json, specification/paths/Shops-shop_id-integrations-integration_id-configuration-schema.json, specification/paths/Shops-shop_id-integrations-integration_id-configuration.json, specification/paths/Shops-shop_id-integrations-integration_id-configure.json, specification/schemas.json, specification/schemas/integrations/ConfigurationSchema.json, specification/schemas/integrations/Integration.json
**Changes**
- ✨ add specification to fetch integration configuration schema for shop
- ✨ add specification to save integration configuration settings for a shop
https://myparcelcombv.atlassian.net/browse/MP-6869
=> :sparkles: Marketplace account configuration API specification

specification/schemas/contract-templates/ContractTemplate.json, specification/schemas/contract-templates/ContractTemplateResponse.json
since there is no PATCH endpoint (yet)
=> 🔥 contract-templates do not need updated_at

specification/schemas/return-methods/ReturnMethod.json
**Changes**
- :sparkles: introduce ReturnMethod title and description
- :fire: remove name
https://myparcelcombv.atlassian.net/browse/MP-6935
=> :sparkles: introduce ReturnMethod title and description

.env.dist, README.md, docker-compose.yml, docker/build/Dockerfile, mp.sh, mp/bundle, mp/help, mp/up, src/myparcelcom.css
- Update to Redoc to v2.2.0 and make the response accordions look like we are used to.
- Port some style/text changes from the carrier-specification.
=> 🐳 Update Redoc

specification/schemas/users/User.json, specification/schemas/users/UserResponse.json
- ✨ Added `has_mfa_enabled` to User schema.
- https://myparcelcombv.atlassian.net/browse/MP-6905
=> :sparkles: Added has_mfa_enabled attribute to user schema.

specification/schemas/shops/Shop.json
https://myparcelcombv.atlassian.net/browse/MP-6950
=> :sparkles: [api-spec] introduced pending_return_email_subscription on shops

specification/schemas/shops/Shop.json, specification/schemas/shops/ShopMeta.json, specification/schemas/shops/ShopResponse.json
https://myparcelcombv.atlassian.net/browse/MP-6973
=> :sparkles: Add custom content for approved return emails to shop

specification/paths/GetDynamicServiceRates.json, specification/paths/MultiColliShipments.json, specification/schemas.json, specification/schemas/shipments/ColliMeta.json
https://myparcelcombv.atlassian.net/browse/MP-6963
=> :sparkles: Introduced meta.colli on the get dynamic rates endpoint

specification/paths/Returns-v1-return-methods.json
https://myparcelcombv.atlassian.net/browse/MP-6901
=> :speech_balloon: Update comment about `shipment` type ReturnMethod country codes

specification/paths/Contracts-contract_id.json, specification/paths/Contracts.json, specification/schemas.json, specification/schemas/contract-templates/ContractTemplateRelationship.json, specification/schemas/contracts/Contract.json
https://myparcelcombv.atlassian.net/browse/MP-6997
**TODO**
=> :twisted_rightwards_arrows: Replace `template` relationship with `contract_template` relationship

specification/paths/Contracts.json
- Added contract-template include on contracts
=> :sparkles: Contract template include on contracts.

specification/paths/Users.json, specification/schemas/users/User.json, specification/schemas/users/UserResponse.json
Reverts MyParcelCOM/api-specification#1147
=> Revert "MP-7072 Last login user attribute"

specification/paths/ServiceRates.json, specification/schemas/service-rates/ServiceRate.json, specification/schemas/service-rates/ServiceRateResponse.json
- Updated the price schema's on the ServiceRate schemas to use BasePrice
- Updated the ServiceRateResponse schema and the POST service rate schema to use Price
=> :lady_beetle: Service rate price amount and currency should be patchable individually

specification/schemas/returns/Return.json, specification/schemas/returns/ReturnResponse.json
https://myparcelcombv.atlassian.net/browse/MP-7105
=> :lady_beetle: Rename `ReturnOrder.addres` to `ReturnOrder.return_address`

specification/schemas/brokers/Broker.json
- Added a new `reply_to_email` field to broker
https://myparcelcombv.atlassian.net/browse/MP-6925?atlOrigin=eyJpIjoiNmQwOWQzNjgwMDA1NDQ2YWIzZDczYmM4Njg4OGY2YmQiLCJwIjoiaiJ9
=> Add reply-to email for brokers

specification/paths/Hooks.json, specification/schemas/brokers/Broker.json
* :memo: Documented hook owner include by @NickVries in https://github.com/MyParcelCOM/api-specification/pull/1169
=> 🚀 Update staging

specification/paths/Brokers-broker_id-carriers.json, specification/paths/Brokers-broker_id.json, specification/paths/Brokers.json
=> :sparkles: MP-7131 Allow users with brokers.manage to get and update brokers

specification/schemas/locales/LocaleEnum.json
https://myparcelcombv.atlassian.net/browse/MP-7240
---
Make Portugal
=> 🇵🇹 Added `pt-PT` to user locales

specification/paths/Shipping-v2-available-delivery-dates.json
https://myparcelcombv.atlassian.net/browse/MP-7273
=> [api-spec] Added carrier code as a required field to the delivery dates endpoint

specification/paths.json, specification/paths/Returns-v1-returns-allow-reissue.json, specification/schemas/statuses/Status.json
- Added a simple endpoint that allows an order reference to be reissued on a shop
=> ✨  Added endpoint that allows an order reference to be reissued as a return

specification/schemas/invitations/Invitation.json, specification/schemas/invitations/InvitationRequest.json, specification/schemas/invitations/InvitationResponse.json
- Added `user_types` attribute to the `Invitation`, `InvitationRequest` and `InvitationResponse` schemas.
- https://myparcelcombv.atlassian.net/browse/MP-7300
=> MP-7300 User types on Invitations

specification/schemas/shipments/BaseCustoms.json
https://myparcelcombv.atlassian.net/browse/MP-7588
=> :sparkles: Add `shipment.customs.payment` data

.github/workflows/ci.yml, docker-compose.yml, docker/build/Dockerfile, docker/json-bundler/Dockerfile
=> ⬆️ Updated node + redoc + actions
